%%
% SPDX-FileCopyrightText: 2024 Matthew Millard <millard.matthew@gmail.com>
%
% SPDX-License-Identifier: MIT
%
%%
function figH = addBrownScottLoeb1996ApneurosisForceLength(...
                figH,subplotPosition, labelData, ...
                expColor,...
                muscleArchitecture, ...
                flag_plotInNormalizedCoordinates)

assert(flag_plotInNormalizedCoordinates==1,...
       ['Error: addBrownScottLoeb1996PassiveForceLength only works in ',...
        'normalized coordinates']);

optimalFiberLength      =muscleArchitecture.lceOpt;
maximumIsometricForce   =muscleArchitecture.fiso;
tendonSlackLength       =muscleArchitecture.ltslk;
pennationAngle          =muscleArchitecture.alpha;

figure(figH);
subplot('Position',subplotPosition);

fileBSL1996fpeN = ['..',filesep,'..',filesep,'..',filesep,'..',filesep,...
           'ReferenceExperiments',filesep,...
           'active_passive_force_length',filesep,...
           'fig_BrownScottLoeb1996_fig3.csv']; 

dataBSL1996fpeN= csvread(fileBSL1996fpeN,1,0);

dataBSL1996fpeN(1,:)=dataBSL1996fpeN(end,:);

%dataBSL1996fpeN(:,1)=fliplr(dataBSL1996fpeN(:,1)')';
%dataBSL1996fpeN(:,2)=fliplr(dataBSL1996fpeN(:,2)')';

fill(dataBSL1996fpeN(:,1),...
     dataBSL1996fpeN(:,2),...
     expColor,...
     'EdgeColor','none',...
     'DisplayName',labelData,...
     'HandleVisibility','on');
hold on;
