function figH = addBrownScottLoeb1996ForceVelocity(...
                figH,subplotPosition, labelData, ...
                expColor,...
                vceMaxExp)




figure(figH);
subplot('Position',subplotPosition);

fileBSL1996fvCN = ['..',filesep,'..',filesep,'..',filesep,'..',filesep,...
           'ReferenceExperiments',filesep,...
           'force_velocity',filesep,...
           'fig_BrownScottLoeb1996_Fig8.csv']; 

fileBSL1996fvEN = ['..',filesep,'..',filesep,'..',filesep,'..',filesep,...
           'ReferenceExperiments',filesep,...
           'force_velocity',filesep,...
           'fig_BrownScottLoeb1996_Fig9.csv']; 


dataBSL1996fvEN= csvread(fileBSL1996fvEN,1,0);
dataBSL1996fvCN= csvread(fileBSL1996fvCN,1,0);

plot(dataBSL1996fvEN(:,1)./vceMaxExp,...
     dataBSL1996fvEN(:,2),...
     's',...
     'Color',expColor,...
     'MarkerFaceColor',[1,1,1],...
     'MarkerSize',4,...
     'DisplayName',labelData,...
     'HandleVisibility','on');
hold on;

plot(dataBSL1996fvCN(:,1)./vceMaxExp,...
     dataBSL1996fvCN(:,2),...
     's',...
     'Color',expColor,...
     'MarkerFaceColor',[1,1,1],...
     'MarkerSize',4,...
     'DisplayName',labelData,...
     'HandleVisibility','off');
hold on;