function figH = addGollapudiLin2009ActiveForceLength(...
    figH,subplotPosition, labelGL2009, expColor,...
    lceOptHuman, muscleArchitecture, ...
    flag_plotInNormalizedCoordinates)

optimalFiberLength      =muscleArchitecture.lceOpt;
maximumIsometricForce   =muscleArchitecture.fiso;
tendonSlackLength       =muscleArchitecture.ltslk;
pennationAngle          =muscleArchitecture.alpha;

figure(figH);
subplot('Position',subplotPosition);

fileGL2009flN = ['..',filesep,'..',filesep,'..',filesep,'..',filesep,...
           'ReferenceExperiments',filesep,...
           'active_passive_force_length',filesep,...
           'GollapudiLin2009_Fig7b.csv'];

dataGL2009FalN = csvread(fileGL2009flN,1,0);

if(flag_plotInNormalizedCoordinates==1)
    lceExpFalN  = (dataGL2009FalN(:,1)./lceOptHuman);
    fceExpFalN  = dataGL2009FalN(:,2);

else
    lceExpFalN  = ...
        (dataGL2009FalN(:,1)./ceOpt)*optimalFiberLength...
       +tendonSlackLength;
    fceExpFalN   = ...
        dataGL2009FalN(:,2).*(maximumIsometricForce);

end

plot(lceExpFalN,...
     fceExpFalN,...
     'o',...
     'LineWidth',0.5,...
     'Color',expColor,...
     'MarkerFaceColor',[1,1,1],...
     'MarkerSize',4,...
     'DisplayName',labelGL2009);
hold on