function figH = addHerzogLeonard1997ForceVelocity(...
                    figH,subplotPosition,labelHL1997,...
                    dataFvSample, ...
                    expColor,...
                    lineWidth,...
                    plotSettings,...
                    musclePropertiesExp)

figure(figH);
subplot('Position',subplotPosition);

fisoExp   = musclePropertiesExp.fiso;
lceOptExp = musclePropertiesExp.lceOpt;
vmaxExp   = musclePropertiesExp.vmax;
plot( dataFvSample(:,1)./vmaxExp,...
      dataFvSample(:,2),...
      '-',...
      'Color',[1,1,1],...
      'MarkerFaceColor',[1,1,1],...
      'LineWidth',lineWidth+1,...
      'DisplayName',labelHL1997,...
      'HandleVisibility','off');   
hold on;
plot( dataFvSample(:,1)./vmaxExp,...
      dataFvSample(:,2),...
      'o',...
      'Color',[1,1,1],...
      'MarkerFaceColor',[1,1,1],...
      'LineWidth',lineWidth,...
      'DisplayName',labelHL1997,...
      'MarkerSize',3,...
      'HandleVisibility','off');   
hold on;
plot( dataFvSample(:,1)./vmaxExp,...
      dataFvSample(:,2),...
      '-',...
      'Color',expColor,...
      'MarkerFaceColor',expColor,...
      'LineWidth',lineWidth,...
      'DisplayName',labelHL1997,...
      'HandleVisibility','on');   
hold on;
plot( dataFvSample(:,1)./vmaxExp,...
      dataFvSample(:,2),...
      'o',...
      'Color',expColor,...
      'MarkerFaceColor',expColor,...
      'LineWidth',lineWidth,...
      'DisplayName',labelHL1997,...
      'MarkerSize',2,...
      'HandleVisibility','off');   
hold on;
legend('Location','NorthWest');     

text(max(plotSettings(1).xLim),...
     min(plotSettings(1).yLim),...
    sprintf('%s: %1.2f%s','$$v^M_{max}',vmaxExp,'\ell^M_o/s$$'),...
    'FontSize',6,...
    'HorizontalAlignment','right',...
    'VerticalAlignment','bottom');
hold on


