function figH = addHerzogLeonard1997KeyPoints(...
                    figH,subplotFl,subplotFpe,labelSeries,expColor,...
                    muscleArchitecture,...
                    flag_plotInNormalizedCoordinates,...
                    addPassive0AddActive1)


assert(flag_plotInNormalizedCoordinates==1);

dataHL1997 = getHerzogLeonard1997Keypoints();

laN = [dataHL1997.l(1);dataHL1997.lMid;dataHL1997.l(2)];
faN = [dataHL1997.fa(1);dataHL1997.faMid;dataHL1997.fa(2)];

figure(figH);

if(addPassive0AddActive1==1)
    subplot('Position',subplotFl);

    plot(laN,faN,...
         'x','Color',expColor,...
         'MarkerFaceColor',expColor,...
         'HandleVisibility','on',...
         'DisplayName',labelSeries);
    hold on;

%     plot(laN,faN,...
%          'x','Color',expColor,...
%          'MarkerFaceColor',expColor,...
%          'DisplayName',labelSeries);
end
if(addPassive0AddActive1==0)
    subplot('Position',subplotFpe);

    plot(dataHL1997.l(2),dataHL1997.fpe(2),...
         'x','Color',expColor,...
         'MarkerFaceColor',expColor,...
         'HandleVisibility','on',...
         'DisplayName',labelSeries);
    hold on;
    
%     plot(dataHL1997.l(2),dataHL1997.fpe(2),...
%          'x','Color',expColor,...
%          'MarkerFaceColor',expColor,...
%          'DisplayName',labelSeries);
end


