function figH = addHerzogLeonard1997ForceVelocity(...
                    figH,subplotPosition,labelHL1997,...
                    dataFvSample, ...
                    expColor,...
                    lineWidth,...
                    plotSettings,...
                    musclePropertiesExp)

%fid=fopen(fileNameToAppendProcessedData,'a');

figure(figH);
subplot('Position',subplotPosition);

fisoExp   = musclePropertiesExp.fiso;
lceOptExp = musclePropertiesExp.lceOpt;
vmaxExp   = musclePropertiesExp.vmax;
% plot( dataFvSample(:,1)./vmaxExp,...
%       dataFvSample(:,2),...
%       '-',...
%       'Color',[1,1,1],...
%       'MarkerFaceColor',[1,1,1],...
%       'LineWidth',lineWidth+1,...
%       'DisplayName',labelHL1997,...
%       'HandleVisibility','off');   
% hold on;
% plot( dataFvSample(:,1)./vmaxExp,...
%       dataFvSample(:,2),...
%       'o',...
%       'Color',[1,1,1],...
%       'MarkerFaceColor',[1,1,1],...
%       'LineWidth',lineWidth,...
%       'DisplayName',labelHL1997,...
%       'MarkerSize',3,...
%       'HandleVisibility','off');   
% hold on;
% plot( dataFvSample(:,1)./vmaxExp,...
%       dataFvSample(:,2),...
%       '-',...
%       'Color',expColor,...
%       'MarkerFaceColor',expColor,...
%       'LineWidth',lineWidth,...
%       'DisplayName',labelHL1997,...
%       'HandleVisibility','on');   
% hold on;
plot( dataFvSample(:,1)./vmaxExp,...
      dataFvSample(:,2),...
      'x',...
      'Color',expColor,...
      'MarkerFaceColor',expColor,...
      'LineWidth',lineWidth,...
      'DisplayName',labelHL1997,...
      'MarkerSize',3,...
      'HandleVisibility','on');   
hold on;
% legend('Location','NorthWest');     




% for indexData=1:1:length(dataFvSample(:,1))
%     fprintf(fid,'%1.3f,%1.3f,%i,%i\n',...
%             dataFvSample(indexData,1)./vmaxExp,...
%             dataFvSample(indexData,2),...
%             idData,1);
% end 
% 
% fclose(fid);
