function figH = addHoltAzizi2014ActiveForceLengthShift(...
                    figH,subplotPosition,peakLceNFalN,labelHA2014,expColor,...
                    muscleArchitecture,...
                    flag_plotInNormalizedCoordinates)

optimalFiberLength      =muscleArchitecture.lceOpt;
maximumIsometricForce   =muscleArchitecture.fiso;
tendonSlackLength       =muscleArchitecture.ltslk;
pennationAngle          =muscleArchitecture.alpha;

figure(figH);
subplot('Position',subplotPosition);

fileHA2014 = ['..',filesep,'..',filesep,'..',filesep,'..',filesep,...
              'ReferenceExperiments',filesep,...
              'active_passive_force_length',filesep,...
              'HoltAzizi2014_Fig2.csv'];            
dataHA2014 = loadDigitizedData(fileHA2014,...
                'Norm. Force ($$f/f^M_o$$)','Norm. Length ($$\ell/\ell^M_o$$)',...
                {'s00','s01','s03','s04'},...
                {'Holt and Azizi 2014'});
if(flag_plotInNormalizedCoordinates==0)
    for idx=1:1:length(dataHA2014)
        dataHA2014(idx).x(:,1)=dataHA2014(idx).x(:,1).*(maximumIsometricForce);
        dataHA2014(idx).y(:,1)=dataHA2014(idx).y(:,1).*(optimalFiberLength)+tendonSlackLength;                    
    end
end        
flag_addReferenceData=0;

angleV = ([0:0.05:1].*(2*pi))';

flag_firstRound=1; %[150,0,24]./256;%[159, 129, 112]./256;
idx=3;
%for idx=1:1:3
    xy0 = [dataHA2014(idx).y(1,:),dataHA2014(idx).x(1,:)];
    xy1 = [dataHA2014(idx).y(2,:),dataHA2014(idx).x(2,:)];
    xy2 = [dataHA2014(idx).y(3,:),dataHA2014(idx).x(3,:)];
    xy3 = [dataHA2014(idx).y(4,:),dataHA2014(idx).x(4,:)];
    xy4 = [dataHA2014(idx).y(5,:),dataHA2014(idx).x(5,:)];

    

    rx = abs(xy3(1,1)-xy2(1,1))*0.5;
    ry = abs(xy1(1,2)-xy0(1,2))*0.5;
    dataEllipse = [rx.*cos(angleV), ry.*sin(angleV)];
    dataEllipse = dataEllipse + xy4;

    fill(dataEllipse(:,1),dataEllipse(:,2),...
         [1,1,1], ...
         'EdgeColor',expColor,...
         'HandleVisibility','off');
    hold on;

    hvis = 'on';
     if(flag_firstRound==1)
         hvis='on';
         flag_firstRound=0;
     end
%         plot([xy0(1,1),xy1(1,1)],...
%              [xy0(1,2),xy1(1,2)],...
%              '-',...
%              'LineWidth',1.5,...
%              'Color',[1,1,1],...
%              'MarkerFaceColor',[1,1,1],...
%              'MarkerSize',4,...
%              'DisplayName',labelHA2014,...
%              'HandleVisibility','off');
%         hold on;
% 
%         plot([xy2(1,1),xy3(1,1)],...
%              [xy2(1,2),xy3(1,2)],...
%              '-',...
%              'LineWidth',1.5,...
%              'Color',[1,1,1],...
%              'MarkerFaceColor',[1,1,1],...
%              'MarkerSize',4,...
%              'DisplayName',labelHA2014,...
%              'HandleVisibility','off');
%         hold on;

    plot([xy0(1,1),xy1(1,1)],...
         [xy0(1,2),xy1(1,2)],...
         '-',...
         'LineWidth',1,...
         'Color',expColor,...
         'MarkerFaceColor',[1,1,1],...
         'MarkerSize',4,...
         'DisplayName',labelHA2014,...
         'HandleVisibility','off');
    hold on;

    plot([xy2(1,1),xy3(1,1)],...
         [xy2(1,2),xy3(1,2)],...
         '-',...
         'LineWidth',1,...
         'Color',expColor,...
         'MarkerFaceColor',[1,1,1],...
         'MarkerSize',4,...
         'DisplayName',labelHA2014,...
         'HandleVisibility','off');
    hold on;

    plot(xy4(1,1),...
         xy4(1,2),...
         'd',...
         'LineWidth',1,...
         'Color',expColor,...
         'MarkerFaceColor',[1,1,1],...
         'MarkerSize',4,...
         'DisplayName',labelHA2014,...
         'HandleVisibility',hvis);
    hold on;
    
%end
%%
%Add annotation
%%
yB=0.25;            
dyB = 0.025;
dxB = 0.025;

if(flag_plotInNormalizedCoordinates==0)
    yB = maximumIsometricForce*0.25;
    dxB = optimalFiberLength*0.025;
    dyB = maximumIsometricForce*0.025;
end

plot([xy4(1,1),xy4(1,1)],...
     [xy4(1,2)-ry,yB],...
     '-',...
     'Color',[1,1,1],...
     'LineWidth',2,...
     'HandleVisibility','off');
hold on;
plot([xy4(1,1),xy4(1,1)],...
     [xy4(1,2)-ry,yB],...
     '-',...
     'Color',[0,0,0],...
     'LineWidth',yB,...
     'HandleVisibility','off');
hold on;            
plot([peakLceNFalN(1,1),peakLceNFalN(1,1)],...
     [peakLceNFalN(1,2),yB],...
     '-',...
     'Color',[1,1,1],...
     'LineWidth',2,...
     'HandleVisibility','off');
hold on;            
plot([peakLceNFalN(1,1),peakLceNFalN(1,1)],...
     [peakLceNFalN(1,2),yB],...
     '-',...
     'Color',[0,0,0],...
     'LineWidth',0.5,...
     'HandleVisibility','off');   
hold on;
plot([xy4(1,1),peakLceNFalN(1,1)],...
     [yB,yB],...
     '-',...
     'Color',[0,0,0],...
     'LineWidth',0.5,...
     'HandleVisibility','off');   
hold on;
plot([xy4(1,1)-dxB],...
     [yB],...
     '>',...
     'Color',[0,0,0],...
     'LineWidth',0.5,...
     'MarkerSize',2,...
     'MarkerFaceColor',[0,0,0],...
     'HandleVisibility','off');   
hold on;
plot([peakLceNFalN(1,1)+dxB],...
     [yB],...
     '<',...
     'Color',[0,0,0],...
     'LineWidth',0.5,...
     'MarkerSize',2,...
     'MarkerFaceColor',[0,0,0],...
     'HandleVisibility','off');   
hold on;     
if(flag_plotInNormalizedCoordinates==1)
    text((xy4(1,1)+peakLceNFalN(1,1))*0.5,...
          yB-dyB,...
          sprintf('%1.2f%s',xy4(1,1)-peakLceNFalN(1,1),'$$\ell^M_o$$'),...
          'FontSize',6,...
          'HorizontalAlignment','center',...
          'VerticalAlignment','top');
    hold on;
else 
    text((xy4(1,1)+peakLceNFalN(1,1))*0.5,...
          yB-dyB,...
          sprintf('%1.2fmm',xy4(1,1)-peakLceNFalN(1,1)),...
          'FontSize',6,...
          'HorizontalAlignment','center',...
          'VerticalAlignment','top');
    hold on;
end
