function figH = addMashimaAkazawaKushimaFujii1972ForceVelocity(figH, ...
                    subplotPosition, labelData,  expColor, vceMaxExp)

figure(figH);
subplot('Position',subplotPosition);

fileMAKF1972fvN = ['..',filesep,'..',filesep,'..',filesep,'..',filesep,...
           'ReferenceExperiments',filesep,...
           'force_velocity',filesep,...
           'MashimaAkazawaKushimaFujii1972_Fig4.csv']; 

dataMAKF1972fvN = loadDigitizedData(fileMAKF1972fvN,...
                'Norm. Force ($$f/f_o^M$$)',...
                'Norm. Velocity ($$v/\ell^M_o$$)',...
                {'c01','c02','c03','c04',...
                 'c05','c06','c07','c08',...
                 'c09','c10','c11','c12',...
                 'c13','c14','c15','c16'},...
                {'Mashima, Akazawa, Kushima, Fujii, 1972'}); 

hVis = 'on';

for idx=1:1:length(dataMAKF1972fvN)

    plot(-dataMAKF1972fvN(idx).y./vceMaxExp,...
         dataMAKF1972fvN(idx).x,...
         '-',...
         'Color',[1,1,1],...
         'LineWidth',1,...
         'DisplayName',labelData,...
         'HandleVisibility','off');
    hold on;
    
    plot(-dataMAKF1972fvN(idx).y./vceMaxExp,...
         dataMAKF1972fvN(idx).x,...
         '.',...
         'Color',[1,1,1],...
         'LineWidth',1,...
         'MarkerSize',5,...
         'MarkerFaceColor',[1,1,1],...
         'DisplayName',labelData,...
         'HandleVisibility','off');
    hold on;

    plot(-dataMAKF1972fvN(idx).y./vceMaxExp,...
         dataMAKF1972fvN(idx).x,...
         '-',...
         'Color',expColor,...
         'LineWidth',0.5,...
         'DisplayName',labelData,...
         'HandleVisibility',hVis);
    hold on;

    plot(-dataMAKF1972fvN(idx).y./vceMaxExp,...
         dataMAKF1972fvN(idx).x,...
         '.',...
         'Color',expColor,...
         'LineWidth',0.5,...
         'MarkerSize',4,...
         'MarkerFaceColor',expColor,...
         'DisplayName',labelData,...
         'HandleVisibility','off');
    hold on;
    
    hVis = 'off';
        
end
