function figH = addMashimaAkazawaKushimaFujii1972ForceVelocity(figH, ...
                    subplotPosition, labelData,  expColor, vceMaxExp,...
                    fileNameToAppendProcessedData,...
                    idData)

figure(figH);
subplot('Position',subplotPosition);

fileMAKF1972fvN = ['..',filesep,'..',filesep,'..',filesep,'..',filesep,...
           'ReferenceExperiments',filesep,...
           'force_velocity',filesep,...
           'MashimaAkazawaKushimaFujii1972_Fig4.csv']; 

dataMAKF1972fvN = loadDigitizedData(fileMAKF1972fvN,...
                'Norm. Force ($$f/f_o^M$$)',...
                'Norm. Velocity ($$v/\ell^M_o$$)',...
                {'c01','c02','c03','c04',...
                 'c05','c06','c07','c08',...
                 'c09','c10','c11','c12',...
                 'c13','c14','c15','c16'},...
                {'Mashima, Akazawa, Kushima, Fujii, 1972'}); 

hVis = 'on';

fid=fopen(fileNameToAppendProcessedData,'a');

for idx=1:1:length(dataMAKF1972fvN)
    vceMean = mean(-dataMAKF1972fvN(idx).y);

    if(vceMean < 0)
        plot(-dataMAKF1972fvN(idx).y./vceMaxExp,...
             dataMAKF1972fvN(idx).x,...
             '-',...
             'Color',[1,1,1],...
             'LineWidth',1,...
             'DisplayName',labelData,...
             'HandleVisibility','off');
        hold on;
        
        plot(-dataMAKF1972fvN(idx).y./vceMaxExp,...
             dataMAKF1972fvN(idx).x,...
             '.',...
             'Color',[1,1,1],...
             'LineWidth',1,...
             'MarkerSize',5,...
             'MarkerFaceColor',[1,1,1],...
             'DisplayName',labelData,...
             'HandleVisibility','off');
        hold on;
    
        plot(-dataMAKF1972fvN(idx).y./vceMaxExp,...
             dataMAKF1972fvN(idx).x,...
             '-',...
             'Color',expColor,...
             'LineWidth',0.5,...
             'DisplayName',labelData,...
             'HandleVisibility',hVis);
        hold on;
    
        plot(-dataMAKF1972fvN(idx).y./vceMaxExp,...
             dataMAKF1972fvN(idx).x,...
             '.',...
             'Color',expColor,...
             'LineWidth',0.5,...
             'MarkerSize',4,...
             'MarkerFaceColor',expColor,...
             'DisplayName',labelData,...
             'HandleVisibility','off');
        hold on;
        
        if(dataMAKF1972fvN(idx).x < 0.75)
            [fmax,idxFmax] = max(dataMAKF1972fvN(idx).x);
            [vmax,idxVmax] = min(-dataMAKF1972fvN(idx).y./vceMaxExp);

            text(-dataMAKF1972fvN(idx).y(idxFmax,1)./vceMaxExp,...
                 dataMAKF1972fvN(idx).x(idxFmax,1),...
                 sprintf('%1.2f',dataMAKF1972fvN(idx).x(idxFmax,1)),...
                 'HorizontalAlignment','left',...
                 'VerticalAlignment', 'middle',...
                 'FontSize',6);
            hold on;
            
            %plot((-dataMAKF1972fvN(idx).y(idxVmax,1)./vceMaxExp).*[1,1],...
            %     [0;0.5],'-k','HandleVisibility','off');
            %hold on;
            th=text(-dataMAKF1972fvN(idx).y(idxVmax,1)./vceMaxExp,...
                 -0.01,...
                 sprintf('%1.2f%s',-dataMAKF1972fvN(idx).y(idxVmax,1)./vceMaxExp),...
                 'HorizontalAlignment','right',...
                 'VerticalAlignment', 'middle',...
                 'FontSize',6);
            hold on;
            th.Rotation=45;
        end

        hVis = 'off';
    
        for indexData=1:1:length(dataMAKF1972fvN(idx).x(:,1))
            fprintf(fid,'%1.3f,%1.3f,%i,%i\n',...
                    -dataMAKF1972fvN(idx).y(indexData,1)./vceMaxExp,...
                     dataMAKF1972fvN(idx).x(indexData,1),...
                     idData,idx);
        end    
    end
        
end

fclose(fid);