function figH = addRackWestbury1969ActiveForceLength(...
                    figH,subplotPosition,peakLceNFalN,...
                    labelRW1969,expColor,...
                    muscleArchitecture,...
                    flag_addLines,...
                    flag_addAnnotation,...
                    flag_plotInNormalizedCoordinates,...
                    fileNameToAppendProcessedData,...
                    idRackWestbury1969)

optimalFiberLength      =muscleArchitecture.lceOpt;
maximumIsometricForce   =muscleArchitecture.fiso;
tendonSlackLength       =muscleArchitecture.ltslk;
pennationAngle          =muscleArchitecture.alpha;

figure(figH);
subplot('Position',subplotPosition);

fileRW1969 = ['..',filesep,'..',filesep,'..',filesep,'..',filesep,...
              'ReferenceExperiments',filesep,...
              'active_passive_force_length',filesep,...
              'RackWestbury1969_Figure8.csv'];            
dataRW1969 = loadDigitizedData(fileRW1969,...
                'Force (kg)','Length (cm)',...
                {'d03','d05','d10','d35','d60',...
                 's03L','s03H','s05L','s05H','s10L','s10H'},...
                {'Rack and Westbury 1969'});

RW1969=struct('fiso',0,'lceOpt',0);
[RW1969.fiso, idx]= max(dataRW1969(4).y);
RW1969.lceOpt    = dataRW1969(4).x(idx,1);
dx=0.05;
if(flag_plotInNormalizedCoordinates==1)
    for idx=1:1:length(dataRW1969)
        dataRW1969(idx).x(:,1)=dataRW1969(idx).x(:,1)./(RW1969.lceOpt);
        dataRW1969(idx).y(:,1)=dataRW1969(idx).y(:,1)./(RW1969.fiso);                    
    end
end

if(flag_plotInNormalizedCoordinates==0)
    kg2N=9.81;
    dx=dx.*optimalFiberLength;
    for idx=1:1:length(dataRW1969)
        dataRW1969(idx).x(:,1)=dataRW1969(idx).x(:,1);
        dataRW1969(idx).y(:,1)=dataRW1969(idx).y(:,1).*(kg2N);                    
    end
end

if(flag_addLines==1)
    seriesLabels = {'3','5','10','35'};
    



    for i=2:2:4

        %Write the maximum isometric force-length relation to file
        if(i==4)
            fid=fopen(fileNameToAppendProcessedData,'a');            
            for j=1:1:length(dataRW1969(i).x)
                fprintf(fid,'%1.3f,%1.3f,%i,%i\n',...
                        dataRW1969(i).x(j,1),...
                        dataRW1969(i).y(j,1),...
                        idRackWestbury1969,1);
            end
            fclose(fid);
        end

        plot(dataRW1969(i).x,dataRW1969(i).y,'-','Color',[1,1,1],...
             'LineWidth',2,'HandleVisibility','off');
        hold on;
        plot(dataRW1969(i).x,dataRW1969(i).y,'o','Color',[1,1,1],...
             'LineWidth',0.1,'MarkerSize',4,...
             'MarkerFaceColor',[1,1,1],...
             'HandleVisibility','off');
        hold on;
        plot(dataRW1969(i).x,dataRW1969(i).y,'-','Color',expColor,...
             'LineWidth',0.5,'HandleVisibility','off');
        hold on;
            
        hvis='off';
        if(i==2)
            hvis='on';
        end
    
        plot(dataRW1969(i).x,dataRW1969(i).y,'o','Color',expColor,...
             'LineWidth',0.1,'MarkerSize',2,...
             'MarkerFaceColor',expColor,...
             'HandleVisibility',hvis,...
             'DisplayName',labelRW1969);
        hold on;  
    
%         text(dataRW1969(i).x(end)+dx,...
%              dataRW1969(i).y(end),...
%              seriesLabels{i},'FontSize',6,...
%              'VerticalAlignment','middle',...
%              'HorizontalAlignment','left');
%         hold on;
    end
end


%%
%Add annotation
%%
if(flag_addAnnotation==1)
    assert(isempty(peakLceNFalN)==0);
    xySubMax = [0,0];
    [xySubMax(1,2),idx] = max(dataRW1969(2).y); 
    xySubMax(1,1)=dataRW1969(2).x(idx,1);
    
    yB=0.25;            
    dyB = 0.025;
    dxB = 0.025;
    
    if(flag_plotInNormalizedCoordinates==0)
        yB = maximumIsometricForce*0.25;
        dxB = optimalFiberLength*0.025;
        dyB = maximumIsometricForce*0.025;
    end
    
    plot([xySubMax(1,1),xySubMax(1,1)],...
         [xySubMax(1,2),yB],...
         '-',...
         'Color',[1,1,1],...
         'LineWidth',2,...
         'HandleVisibility','off');
    hold on;
    plot([xySubMax(1,1),xySubMax(1,1)],...
         [xySubMax(1,2),yB],...
         '-',...
         'Color',[0,0,0],...
         'LineWidth',yB,...
         'HandleVisibility','off');
    hold on;            
    plot([peakLceNFalN(1,1),peakLceNFalN(1,1)],...
         [peakLceNFalN(1,2),yB],...
         '-',...
         'Color',[1,1,1],...
         'LineWidth',2,...
         'HandleVisibility','off');
    hold on;            
    plot([peakLceNFalN(1,1),peakLceNFalN(1,1)],...
         [peakLceNFalN(1,2),yB],...
         '-',...
         'Color',[0,0,0],...
         'LineWidth',0.5,...
         'HandleVisibility','off');   
    hold on;
    plot([xySubMax(1,1),peakLceNFalN(1,1)],...
         [yB,yB],...
         '-',...
         'Color',[0,0,0],...
         'LineWidth',0.5,...
         'HandleVisibility','off');   
    hold on;
    plot([xySubMax(1,1)-dxB],...
         [yB],...
         '>',...
         'Color',[0,0,0],...
         'LineWidth',0.5,...
         'MarkerSize',2,...
         'MarkerFaceColor',[0,0,0],...
         'HandleVisibility','off');   
    hold on;
    plot([peakLceNFalN(1,1)+dxB],...
         [yB],...
         '<',...
         'Color',[0,0,0],...
         'LineWidth',0.5,...
         'MarkerSize',2,...
         'MarkerFaceColor',[0,0,0],...
         'HandleVisibility','off');   
    hold on;     
    if(flag_plotInNormalizedCoordinates==1)
        text((xySubMax(1,1)+peakLceNFalN(1,1))*0.5,...
              yB-dyB,...
              sprintf('%1.2f%s',xySubMax(1,1)-peakLceNFalN(1,1),'$$\ell^M_o$$'),...
              'FontSize',6,...
              'HorizontalAlignment','center',...
              'VerticalAlignment','top');
        hold on;
    else 
        text((xySubMax(1,1)+peakLceNFalN(1,1))*0.5,...
              yB-dyB,...
              sprintf('%1.2fmm',xySubMax(1,1)-peakLceNFalN(1,1)),...
              'FontSize',6,...
              'HorizontalAlignment','center',...
              'VerticalAlignment','top');
        hold on;
    end
end