function figH = addSmeulders2004ActiveForceLength(figH,subplotPosition, ...
                    labelSKHHH2004, expColor,...
                    muscleArchitecture,...
                    flag_plotInNormalizedCoordinates)

optimalFiberLength      =muscleArchitecture.lceOpt;
maximumIsometricForce   =muscleArchitecture.fiso;
tendonSlackLength       =muscleArchitecture.ltslk;
pennationAngle          =muscleArchitecture.alpha;

figure(figH);
subplot('Position',subplotPosition);

fileSKHHH2004 = ['..',filesep,'..',filesep,'..',filesep,'..',filesep,...
           'ReferenceExperiments',filesep,...
           'active_passive_force_length',filesep,...
           'SmeuldersKreulenHageHuijingHorst2004_Fig4.csv'];

dataSKHHH2004 = loadDigitizedData(fileSKHHH2004,...
                'Length (cm)','Norm. Force ($$f/f^M_o$$)',...
                {'falLow','falMean','falHigh'},...
                {'Smeulders et al. 2004'});


%Smeulders et al. reports the total MTU length at which lopt occurs,
%which is not the same as the fiber length. Feiden et al. report
%the optimal fiber length of the FCU as
%
% Fridén J, Lovering RM, Lieber RL. Fiber length variability within the 
% flexor carpi ulnaris and flexor carpi radialis muscles: implications 
% for surgical tendon transfer. The Journal of hand surgery. 
% 2004 Sep 1;29(5):909-14.
% 63.1 ± 4.0 mm
lceOptMean = 6.31;


if(flag_plotInNormalizedCoordinates==1)
    

    xFill = [dataSKHHH2004(1).x;...
             fliplr(dataSKHHH2004(3).x')'];
    yFill = [dataSKHHH2004(1).y;...
             fliplr(dataSKHHH2004(3).y')'];
    fill(xFill./lceOptMean + 1,...
         yFill./100,...
         [1,1,1],...
         'DisplayName',labelSKHHH2004,...
         'EdgeColor',[0,0,0],...
         'HandleVisibility','on');
    hold on;


else
    subplot('Position',reshape(subPlotLayout(indexRow,2,:),1,4));

    xFill = [dataSKHHH2004(1).x;...
             fliplr(dataSKHHH2004(3).x')'];
    yFill = [dataSKHHH2004(1).y;...
             fliplr(dataSKHHH2004(3).y')'];
    fill((xFill./lceOptMean + 1),...
         (yFill./100).*maximumIsometricForce,...
         [1,1,1],...
         'DisplayName',labelSKHHH2004,...
         'EdgeColor',[0,0,0],...
         'HandleVisibility','on');
    hold on;

end   
