function figH = addSimulationActiveForceLength(...
                    figH,subplotPosition,dataForceLength,displayNameStr,...
                    muscleArchitecture,...
                    lineAndMarkerSettings,...
                    plotSettings,...
                    flag_plotInNormalizedCoordinates)

optimalFiberLength      =muscleArchitecture.lceOpt;
maximumIsometricForce   =muscleArchitecture.fiso;
tendonSlackLength       =muscleArchitecture.ltslk;
pennationAngle          =muscleArchitecture.alpha;

lineType        = lineAndMarkerSettings.lineType        ;
lineColor       = lineAndMarkerSettings.lineColor       ;
lineWidth       = lineAndMarkerSettings.lineWidth       ;
markerType      = lineAndMarkerSettings.mark            ;
markerFaceColor = lineAndMarkerSettings.markerFaceColor ;
markerLineWidth = lineAndMarkerSettings.markerLineWidth ;
markerSize      = lineAndMarkerSettings.markerSize      ;


figure(figH);
subplot('Position',subplotPosition);

idxX = 2;
idxY = 3;
if(flag_plotInNormalizedCoordinates==1)
    idxX = 4;
    idxY = 5;
end

plot(dataForceLength(:,idxX),dataForceLength(:,idxY),...
     '-',...
    'Color',[1,1,1],...
    'LineWidth',lineWidth+2,...
    'DisplayName',displayNameStr,...
    'HandleVisibility','off');
hold on;
plot(dataForceLength(:,idxX),dataForceLength(:,idxY),...
     lineType,...
    'Color',lineColor,...
    'LineWidth',lineWidth,...
    'DisplayName',displayNameStr,...
    'HandleVisibility','on',...
    'MarkerFaceColor',markerFaceColor,...
    'MarkerSize',markerSize);
hold on;

for idxPoint=1:1:size(dataForceLength,1)
    plot(dataForceLength(idxPoint,idxX),dataForceLength(idxPoint,idxY),...
         markerType,...
        'Color',[1,1,1],...
        'LineWidth',markerLineWidth,...
        'DisplayName',displayNameStr,...
        'HandleVisibility','off',...
        'MarkerFaceColor',[1,1,1],...
        'MarkerSize',markerSize+2);
    hold on;

    plot(dataForceLength(idxPoint,idxX),dataForceLength(idxPoint,idxY),...
         markerType,...
        'Color',lineColor,...
        'LineWidth',markerLineWidth,...
        'DisplayName',displayNameStr,...
        'HandleVisibility','off',...
        'MarkerFaceColor',markerFaceColor,...
        'MarkerSize',markerSize);
    hold on;
end

[valMax,idxMax] = max(dataForceLength(:,3));

idx=2;
xDelta=abs(diff(plotSettings(idx).xLim))*0.05;
yDelta=abs(diff(plotSettings(idx).yLim))*0.05;            
xText = min(plotSettings(idx).xLim)+0.5*xDelta;

text(xText,max(dataForceLength(:,idxY))-yDelta*0.5,...
     sprintf('%s: %1.0f mm\n%s: %1.1f N',...
     '$$\ell^{*}$$',dataForceLength(idxMax,4)*(optimalFiberLength*1000),...
     '$$f^{*}$$',dataForceLength(idxMax,3)),...
     'HorizontalAlignment','left',...
     'VerticalAlignment','top',...
     'FontSize',6);
hold on;


plot([xText,dataForceLength(idxMax,idxX)],...
     [1,1].*dataForceLength(idxMax,idxY),...
     '-',...
    'Color',[1,1,1],...
    'LineWidth',0.5+2,...
    'DisplayName','',...
    'HandleVisibility','off');
hold on;            
plot([xText,dataForceLength(idxMax,idxX)],...
     [1,1].*dataForceLength(idxMax,idxY),...
     '-',...
    'Color',[0,0,0],...
    'LineWidth',0.5,...
    'DisplayName','',...
    'HandleVisibility','off');
hold on;



