%%
% SPDX-FileCopyrightText: 2024 Matthew Millard <millard.matthew@gmail.com>
%
% SPDX-License-Identifier: MIT
%
%%
function figH = addScottBrownLoeb1996ForceVelocity(...
                figH,subplotPosition, labelData, ...
                expColor,...
                vceMaxExp,...
                fileNameToAppendProcessedData,...
                idData)


fid=fopen(fileNameToAppendProcessedData,'a');

figure(figH);
subplot('Position',subplotPosition);

fileSBL1996fvN = ['..',filesep,'..',filesep,'..',filesep,'..',filesep,...
           'ReferenceExperiments',filesep,...
           'force_velocity',filesep,...
           'fig_ScottBrownLoeb1996_fig4.csv']; 


dataSBL1996fvN = csvread(fileSBL1996fvN,1,0); 



plot(dataSBL1996fvN(:,1)./vceMaxExp,...
     dataSBL1996fvN(:,2),...
     'o',...
     'Color',expColor,...
     'MarkerFaceColor',expColor,...
     'MarkerSize',4,...
     'DisplayName',labelData,...
     'HandleVisibility','on');
hold on;

for indexData=1:1:length(dataSBL1996fvN(:,1))
    fprintf(fid,'%1.3f,%1.3f,%i,%i\n',...
            dataSBL1996fvN(indexData,1)./vceMaxExp,...
            dataSBL1996fvN(indexData,2),...
            idData,1);
end

fclose(fid);
