function figH = addScottBrownLoeb1996PassiveForceLength(...
                figH,subplotPosition, labelData, ...
                expColorA,expColorB,...
                muscleArchitecture, ...
                flag_plotInNormalizedCoordinates)

assert(flag_plotInNormalizedCoordinates==1,...
       ['Error: addScottBrownLoeb1996ActiveForceLength only works in ',...
        'normalized coordinates']);

optimalFiberLength      =muscleArchitecture.lceOpt;
maximumIsometricForce   =muscleArchitecture.fiso;
tendonSlackLength       =muscleArchitecture.ltslk;
pennationAngle          =muscleArchitecture.alpha;

figure(figH);
subplot('Position',subplotPosition);

fileSBL1996flN = ['..',filesep,'..',filesep,'..',filesep,'..',filesep,...
           'ReferenceExperiments',filesep,...
           'active_passive_force_length',filesep,...
           'fig_ScottBrownLoeb1996_fig3.csv']; 


dataSBL1996flN = loadDigitizedData(fileSBL1996flN,...
                'Norm. Length ($$\ell/\ell^M_o$$)','Norm. Force ($$f/f_o^M$$)',...
                {'fl08','fl09','fl10','fl11','fl12',...
                 'fp08','fp09','fp10','fp11','fp12'},...
                {'Scott,Brown,Loeb 1996'}); 


count=1;
countMax = 5;
settingHandleVisibility = 'on';
for idx=1:1:length(dataSBL1996flN)
    if(contains(dataSBL1996flN(idx).seriesName,'fp')==1)
        n = (count-1)/(5-1);
        expColor = expColorA.*n + expColorB.*(1-n);

        plot( dataSBL1996flN(idx).x(:,1),...
              dataSBL1996flN(idx).y(:,1),...
              'o',...
              'Color',expColor,...
              'MarkerFaceColor',expColor,...
              'MarkerSize',4,...
              'DisplayName',labelData,...
              'HandleVisibility',settingHandleVisibility);   
        hold on;
        settingHandleVisibility = 'off';

        count=count+1;
    end
end