function figH = addSimulationActiveForceTimeSeries(...
    figH,subplotPosition,lsdynaMuscleUniform,...
            indexPassiveSample,indexActiveSample,...
            timePassiveSample,timeActiveSample,timeEnd,...
            muscleArchitecture,...
            lineType,lineWidthModel,lineColor,...
            markerSize,markerLineWidth,markerFaceColor,...
            plotSettings,...
            flag_plotInNormalizedCoordinates)

optimalFiberLength      =muscleArchitecture.lceOpt;
maximumIsometricForce   =muscleArchitecture.fiso;
tendonSlackLength       =muscleArchitecture.ltslk;
pennationAngle          =muscleArchitecture.alpha;

figure(figH);
subplot('Position',subplotPosition);

timePlot = lsdynaMuscleUniform.eloutTime(:,1);
if(flag_plotInNormalizedCoordinates==1)
    forcePlot=lsdynaMuscleUniform.eloutAxialBeamForceNorm(:,1);
else
    forcePlot=lsdynaMuscleUniform.eloutAxialBeamForceNorm(:,1).*maximumIsometricForce;
end

plot(   timePlot,...
        forcePlot,...
        lineType,...
        'Color',lineColor,...
        'LineWidth',lineWidthModel,...
        'DisplayName',[lsdynaMuscleUniform.nameLabel,sprintf('(%1.1f)',lsdynaMuscleUniform.act(end,1))],...
        'HandleVisibility','on');
hold on;



if(flag_plotInNormalizedCoordinates==1)
    fAN = lsdynaMuscleUniform.eloutAxialBeamForceNorm(indexPassiveSample,1);
    fA  = fAN;
    fBN = lsdynaMuscleUniform.eloutAxialBeamForceNorm(indexActiveSample,1);
    fB  = fBN;
else
    fAN = lsdynaMuscleUniform.eloutAxialBeamForceNorm(indexPassiveSample,1);
    fA  = fAN.*maximumIsometricForce;
    fBN = lsdynaMuscleUniform.eloutAxialBeamForceNorm(indexActiveSample,1);
    fB  = fBN.*maximumIsometricForce;
end

plot(timePassiveSample,fA,...
     lsdynaMuscleUniform.mark,...
     'Color',lineColor,...
     'MarkerFaceColor',lineColor,...
     'LineWidth',lineWidthModel,...
     'MarkerSize',markerSize,...
     'HandleVisibility','off');
hold on;
text(timePassiveSample,fA,'A',...
     'HorizontalAlignment','center',...
     'VerticalAlignment','bottom',...
     'Color',lineColor);
hold on;

plot(timeActiveSample,fB,...
     lsdynaMuscleUniform.mark,...
     'Color',lineColor,...
     'MarkerFaceColor',lineColor,...             
     'LineWidth',lineWidthModel,...
     'MarkerSize',markerSize,...
     'HandleVisibility','off');
hold on;

text(timeActiveSample,fB,'B',...
     'HorizontalAlignment','center',...
     'VerticalAlignment','bottom',...
     'Color',lineColor);
hold on;

if(timeEnd > 10)
    xlabel('Time (ms)');            
else
    xlabel('Time (s)');
end

if(flag_plotInNormalizedCoordinates==1)
    ylabel('Norm. Tendon Force ($$f^T/f^T_o$$)');
else
    ylabel('Tendon Force (N)');
end
  
title('C. Example time series data');        

box off;

idx=3;
xlim(plotSettings(idx).xLim);
ylim(plotSettings(idx).yLim);
xticks(plotSettings(idx).xTicks);
yticks(plotSettings(idx).yTicks);      

