function figH = addSimulationForceVelocity(...
                    figH,subplotPosition,...
                    dataFv, ...
                    lsdynaMuscleUniform,...
                    lineAndMarkerSettings)

figure(figH);
subplot('Position',subplotPosition);


[valMap,idxMap] = sort(dataFv(:,4));
act = dataFv(1,2);

displayNameStr = [lsdynaMuscleUniform.nameLabel, sprintf('(%1.1f)',act)]; 

plot(dataFv(idxMap,4),...
     dataFv(idxMap,5),...
     '-',...
    'Color',[1,1,1],...
    'LineWidth',lineAndMarkerSettings.lineWidth+1,...
    'DisplayName',displayNameStr,...
    'HandleVisibility','off'); 
hold on;
plot(dataFv(idxMap,4),...
     dataFv(idxMap,5),...
     lsdynaMuscleUniform.mark,...
    'Color',[1,1,1],...
    'LineWidth',lineAndMarkerSettings.lineWidth,...
    'DisplayName',displayNameStr,...
    'HandleVisibility','off',...
    'MarkerFaceColor',[1,1,1],...
    'MarkerSize',lineAndMarkerSettings.markerSize+2);
hold on;
plot(dataFv(idxMap,4),...
     dataFv(idxMap,5),...
     lineAndMarkerSettings.lineType,...
    'Color',lineAndMarkerSettings.lineColor,...
    'LineWidth',lineAndMarkerSettings.lineWidth,...
    'DisplayName',displayNameStr,...
    'HandleVisibility','on',...
    'MarkerFaceColor',lineAndMarkerSettings.markerFaceColor,...
    'MarkerSize',lineAndMarkerSettings.markerSize); 
hold on;
plot(dataFv(idxMap,4),...
     dataFv(idxMap,5),...
     lsdynaMuscleUniform.mark,...
    'Color',lineAndMarkerSettings.lineColor,...
    'LineWidth',lineAndMarkerSettings.lineWidth,...
    'DisplayName',displayNameStr,...
    'HandleVisibility','off',...
    'MarkerFaceColor',lineAndMarkerSettings.markerFaceColor,...
    'MarkerSize',lineAndMarkerSettings.markerSize); 
hold on;
box off;  