function figH = addScottBrownLoeb1996ForceVelocity(...
                figH,subplotPosition, labelData, ...
                expColor,...
                vceMaxExp)



figure(figH);
subplot('Position',subplotPosition);

fileSBL1996fvN = ['..',filesep,'..',filesep,'..',filesep,'..',filesep,...
           'ReferenceExperiments',filesep,...
           'force_velocity',filesep,...
           'fig_ScottBrownLoeb1996_fig4.csv']; 


dataSBL1996fvN = csvread(fileSBL1996fvN,1,0); 



plot(dataSBL1996fvN(:,1)./vceMaxExp,...
     dataSBL1996fvN(:,2),...
     'o',...
     'Color',expColor,...
     'MarkerFaceColor',expColor,...
     'MarkerSize',4,...
     'DisplayName',labelData,...
     'HandleVisibility','on');
hold on;

