function figH = addWinters2011ActiveForceLengthData(...
                        figH,subplotPosition, labelWTLW2011,...
                        expColorA, expColorB,...
                        muscleArchitecture, ...
                        flag_plotInNormalizedCoordinates)

optimalFiberLength      =muscleArchitecture.lceOpt;
maximumIsometricForce   =muscleArchitecture.fiso;
tendonSlackLength       =muscleArchitecture.ltslk;
pennationAngle          =muscleArchitecture.alpha;

figure(figH);
subplot('Position',subplotPosition);

fileWTLW2011EDLIIflN = ['..',filesep,'..',filesep,'..',filesep,'..',filesep,...
           'ReferenceExperiments',filesep,...
           'active_passive_force_length',filesep,...
           'TMWinters2011_EDLII_falN.csv'];

fileWTLW2011EDLflN = ['..',filesep,'..',filesep,'..',filesep,'..',filesep,...
           'ReferenceExperiments',filesep,...
           'active_passive_force_length',filesep,...
           'TMWinters2011_EDL_falN.csv'];

fileWTLW2011TAflN = ['..',filesep,'..',filesep,'..',filesep,'..',filesep,...
           'ReferenceExperiments',filesep,...
           'active_passive_force_length',filesep,...
           'TMWinters2011_TA_falN.csv'];

dataWTLW2011EDLIIFalN   = csvread(fileWTLW2011EDLIIflN,1,0);
dataWTLW2011EDLFalN     = csvread(fileWTLW2011EDLflN,1,0);
dataWTLW2011TAFalN      = csvread(fileWTLW2011TAflN,1,0);

if(flag_plotInNormalizedCoordinates==1)
    lceExpEDLIIFalN  = (dataWTLW2011EDLIIFalN(:,1).*(1/100)+1);
    fceExpEDLIIFalN  = dataWTLW2011EDLIIFalN(:,2).*(1/100);

    lceExpEDLFalN  = (dataWTLW2011EDLFalN(:,1).*(1/100)+1);
    fceExpEDLFalN  = dataWTLW2011EDLFalN(:,2).*(1/100);

    lceExpTAFalN  = (dataWTLW2011TAFalN(:,1).*(1/100)+1);
    fceExpTAFalN  = dataWTLW2011TAFalN(:,2).*(1/100);    
else
    lceExpEDLIIFalN  = ...
    (dataWTLW2011EDLIIFalN(:,1).*(1/100)+1)*optimalFiberLength...
       +tendonSlackLength;
    fceExpEDLIIFalN   = ...
        dataWTLW2011EDLIIFalN(:,2).*(1/100).*(maximumIsometricForce);

    lceExpEDLFalN  = ...
        (dataWTLW2011EDLFalN(:,1).*(1/100)+1)*optimalFiberLength...
       +tendonSlackLength;
    fceExpEDLFalN   = ...
        dataWTLW2011EDLFalN(:,2).*(1/100).*(maximumIsometricForce);
    
    lceExpTAFalN  = ...
        (dataWTLW2011TAFalN(:,1).*(1/100)+1)*optimalFiberLength...
       +tendonSlackLength;
    fceExpTAFalN   = ...
        dataWTLW2011TAFalN(:,2).*(1/100).*(maximumIsometricForce);

end

n = 0;
expColor = expColorA.*(1-n) + expColorB.*n;


subplot('Position',subplotPosition);
plot(lceExpEDLIIFalN,...
     fceExpEDLIIFalN,...
     '.',...
     'Color',expColor,...
     'MarkerFaceColor',expColor,...
     'MarkerSize',8,...
     'DisplayName',[labelWTLW2011,'EDLII'],...
     'HandleVisibility','off');
hold on


n = 0.5;
expColor = expColorA.*(1-n) + expColorB.*n;

plot(lceExpEDLFalN,...
     fceExpEDLFalN,...
     '.',...
     'Color',expColor,...
     'MarkerFaceColor',expColor,...
     'MarkerSize',8,...
     'DisplayName',[labelWTLW2011,'(EDL)'],...
     'HandleVisibility','off');
hold on


n = 1;
expColor = expColorA.*(1-n) + expColorB.*n;

plot(lceExpTAFalN,...
     fceExpTAFalN,...
     '.',...
     'Color',expColor,...
     'MarkerFaceColor',expColor,...
     'MarkerSize',8,...
     'DisplayName',labelWTLW2011);
hold on

