function [figPublication,...
          flag_figPublicationDirty] ...
            = generatePublicationPlots(...
                    figPublication,...
                    simulationTypeStr,...
                    impedanceInputFunctions,...
                    binout,uniformModelData,d3hspFileName,...
                    indexModel,subPlotPanelPublication,...
                    numberOfVerticalPlotRowsPublication,...
                    numberOfHorizontalPlotColumnsPublication,... 
                    simulationDirectoryName,...
                    indexSimulationTrial,...
                    numberOfSimulationDirectories,...
                    commonParameterFolder,...
                    referenceDataFolder,...
                    referenceCurveFolder,...
                    muscleArchitecture,...
                    flag_figPublicationDirty,...
                    simulationColorA, simulationColorB,...
                    dataColorA, dataColorB)



switch (simulationTypeStr)
    case 'eccentric_HerzogLeonard2002'
        flag_addSimulationData  = 1;
        flag_addReferenceData   = 1;                
        if(flag_figPublicationDirty==1)
            flag_addReferenceData = 0;
        end

        indexModel=1;

        [figPublication] =...
            plotEccentricSimulationDataForPublication(figPublication,...
                binout,uniformModelData,d3hspFileName,...
                indexModel,subPlotPanelPublication,...
                numberOfVerticalPlotRowsPublication,...
                numberOfHorizontalPlotColumnsPublication,...                              
                simulationDirectoryName,...
                indexSimulationTrial,... 
                numberOfSimulationDirectories,...
                commonParameterFolder,...
                referenceDataFolder,...         
                referenceCurveFolder,...
                muscleArchitecture,...
                flag_addReferenceData,flag_addSimulationData,...
                simulationColorA,simulationColorB,...
                dataColorA,dataColorB);


        flag_figPublicationDirty=1;
        
    case 'concentric_Guenther2007'
        disp('No concentric publication plot');
    case 'isometric_Guenther2007'
        disp('No isometric publication plot');
    case 'quickrelease_Guenther2007'
        disp('No quickrelease publication plot'); 
    case 'force_length'
        disp('No force_length publication plot'); 
    case 'sinusoid'
        disp('No sinusoid publication plot'); 
    case 'reflex'    
        disp('No reflex publication plot'); 
    case 'reflex_kN_mm_ms'    
        disp('No reflex_kN_mm_ms publication plot'); 
    case 'active_passive_force_length_viva'  

        flag_addSimulationData  = 1;
        flag_addReferenceData   = 1;                
        if(flag_figPublicationDirty==1)
            flag_addReferenceData = 0;
        end


        [figPublication] = ...
            plotActivePassiveForceLengthSimulationDataForPublicationViva(...
                figPublication,...
                binout,uniformModelData,d3hspFileName,...
                indexModel,subPlotPanelPublication,...
                numberOfVerticalPlotRowsPublication,...
                numberOfHorizontalPlotColumnsPublication,...                              
                simulationDirectoryName,...
                indexSimulationTrial, numberOfSimulationDirectories,...
                referenceDataFolder,...         
                referenceCurveFolder,...
                muscleArchitecture,...
                flag_addReferenceData,flag_addSimulationData,...
                simulationColorA,simulationColorB,...
                dataColorA,dataColorB);    
        
        flag_figPublicationDirty=1;

    case 'force_velocity_viva'
        flag_addSimulationData  = 1;
        flag_addReferenceData   = 1;                
        if(flag_figPublicationDirty==1)
            flag_addReferenceData = 0;
        end


        [figPublication] = ...
            plotForceVelocitySimulationDataForPublicationViva(...
                figPublication,...
                binout,uniformModelData,d3hspFileName,...
                indexModel,subPlotPanelPublication,...
                numberOfVerticalPlotRowsPublication,...
                numberOfHorizontalPlotColumnsPublication,...                              
                simulationDirectoryName,...
                indexSimulationTrial, numberOfSimulationDirectories,...
                referenceDataFolder,...         
                referenceCurveFolder,...
                muscleArchitecture,...
                flag_addReferenceData,flag_addSimulationData,...
                simulationColorA,simulationColorB,...
                dataColorA,dataColorB);    
        
        flag_figPublicationDirty=1;    

    case 'active_passive_force_length'  

        flag_addSimulationData  = 1;
        flag_addReferenceData   = 1;                
        if(flag_figPublicationDirty==1)
            flag_addReferenceData = 0;
        end


        [figPublication] = ...
            plotActivePassiveForceLengthSimulationDataForPublication(...
                figPublication,...
                binout,uniformModelData,d3hspFileName,...
                indexModel,subPlotPanelPublication,...
                numberOfVerticalPlotRowsPublication,...
                numberOfHorizontalPlotColumnsPublication,...                              
                simulationDirectoryName,...
                indexSimulationTrial, numberOfSimulationDirectories,...
                referenceDataFolder,...         
                referenceCurveFolder,...
                muscleArchitecture,...
                flag_addReferenceData,flag_addSimulationData,...
                simulationColorA,simulationColorB,...
                dataColorA,dataColorB);    
        
        flag_figPublicationDirty=1;

    case 'force_velocity'
        flag_addSimulationData  = 1;
        flag_addReferenceData   = 1;                
        if(flag_figPublicationDirty==1)
            flag_addReferenceData = 0;
        end


        [figPublication] = ...
            plotForceVelocitySimulationDataForPublicationV2(...
                figPublication,...
                binout,uniformModelData,d3hspFileName,...
                indexModel,subPlotPanelPublication,...
                numberOfVerticalPlotRowsPublication,...
                numberOfHorizontalPlotColumnsPublication,...                              
                simulationDirectoryName,...
                indexSimulationTrial, numberOfSimulationDirectories,...
                referenceDataFolder,...         
                referenceCurveFolder,...
                muscleArchitecture,...
                flag_addReferenceData,flag_addSimulationData,...
                simulationColorA,simulationColorB,...
                dataColorA,dataColorB);    
        
        flag_figPublicationDirty=1;      

    case 'impedance_Kirsch1994'
        flag_addSimulationData  = 1;
        flag_addReferenceData   = 1;                
        if(flag_figPublicationDirty==1)
            flag_addReferenceData = 0;
        end        

        [figPublication] = ...
            plotImpedanceSimulationDataForPublication(figPublication,...
                impedanceInputFunctions,...
                binout,uniformModelData,d3hspFileName, ...
                indexModel,subPlotPanelPublication,...
                numberOfVerticalPlotRowsPublication,...
                numberOfHorizontalPlotColumnsPublication,...                     
                simulationDirectoryName,...
                indexSimulationTrial, numberOfSimulationDirectories,...
                referenceDataFolder,...                       
                referenceCurveFolder,...
                muscleArchitecture,...
                flag_addReferenceData,...
                flag_addSimulationData,...
                simulationColorA,simulationColorB,...
                dataColorA,dataColorB); 

        flag_figPublicationDirty=1;          
end