function figH = plotImpedanceSimulationData(figH,...
                      inputFunctions,...
                      lsdynaBinout,lsdynaMuscle,d3hspFileName, ...
                      indexColumn,...
                      subPlotLayout,subPlotRows,subPlotColumns,...                      
                      simulationFile,indexSimulation, totalSimulations,... 
                      referenceDataFolder,...   
                      optimalFiberLength, maximumIsometricForce, tendonSlackLength,...
                      flag_addReferenceData,...
                      flag_addSimulationData)

figure(figH);


%% Get the columns of musout
indexMusoutTime     = getColumnIndex('time',lsdynaMuscle.columnNames);
indexMusoutStim     = getColumnIndex('stim_tot',lsdynaMuscle.columnNames);
indexMusoutQ        = getColumnIndex('q',lsdynaMuscle.columnNames); %activation
indexMusoutFmtc     = getColumnIndex('f_mtc',lsdynaMuscle.columnNames);
indexMusoutFce      = getColumnIndex('f_ce',lsdynaMuscle.columnNames);
indexMusoutFpee     = getColumnIndex('f_pee',lsdynaMuscle.columnNames);
indexMusoutFsee     = getColumnIndex('f_see',lsdynaMuscle.columnNames);
indexMusoutFsde     = getColumnIndex('f_sde',lsdynaMuscle.columnNames);
indexMusoutLmtc     = getColumnIndex('l_mtc',lsdynaMuscle.columnNames);
indexMusoutLce      = getColumnIndex('l_ce',lsdynaMuscle.columnNames);
indexMusoutLmtcDot  = getColumnIndex('dot_l_mtc',lsdynaMuscle.columnNames);
indexMusoutLceDot   = getColumnIndex('dot_l_ce',lsdynaMuscle.columnNames);

config=getConfiguration();

assert(length(lsdynaBinout.nodout.time) ...
    ==length(lsdynaBinout.elout.beam.time));

nominalLength = getParameterValueFromD3HSPFile(d3hspFileName,'PATHLENN'); % by construction
nominalForce    = lsdynaBinout.elout.beam.axial(end,1);    
activation      = lsdynaMuscle.data(end,indexMusoutQ);


% Add the simulation data
if(flag_addSimulationData==1)
    n = (indexSimulation-1)/(totalSimulations-1);
    %simulationColor = (1-n).*simulationColorA + (n).*simulationColorB;
    


    
    dt= max(diff(lsdynaBinout.elout.beam.time));
    freqRelErr = ((1/dt)-inputFunctions.sampleFrequency)/inputFunctions.sampleFrequency;   
    assert(freqRelErr <= 1e-5);

    freqSimData = calcSignalGainAndPhase(...
                        lsdynaBinout.elout.beam.axial(2:end,1),...
                        nominalLength,...
                        nominalForce,...                        
                        activation,...
                        config.amplitudeMM,...
                        config.bandwidthHz,...
                        inputFunctions);


    if( (config.bandwidthHz == 90 && config.amplitudeMM == 1.6) ...
         || (config.bandwidthHz == 15 && config.amplitudeMM == 1.6) )



        referenceForce = 5;
        forceError = abs(referenceForce-nominalForce)/referenceForce;
        if( forceError < 0.1)

            figH = plotFrequencyResponse(...
                                  figH,...
                                  config,...
                                  inputFunctions,...                                           
                                  freqSimData,... 
                                  nominalForce,...
                                  indexColumn,...
                                  subPlotLayout,...
                                  referenceDataFolder,...
                                  0,...
                                  flag_addSimulationData); 
        end


    end
    if(config.bandwidthHz == 35 && config.amplitudeMM == 0.8)
      [success] = plotStiffnessDamping(...
                            dataFolder,...
                            freqSeriesFiles_RT,...
                            freqSeriesName_RT,...
                            freqSeriesColor_RT,...
                            freqSeriesFiles_ET,...
                            freqSeriesName_ET,...
                            freqSeriesColor_ET,...                        
                            inputFunctions,...                      
                            normFiberLength,...
                            nominalForce,...  
                            dataKBR1994Fig12K,...
                            dataKBR1994Fig12D,...   
                            flag_useElasticTendon,...
                            strFittingBandwidth,...
                            plotLayoutSettings,...
                            plotFolder);

    end

    %flag_frequencyAnalysisMuscleModelsPlotKD,...
    %flag_frequencyAnalysisMuscleModelsPlotAll,...
end

if(flag_addReferenceData==1)

    figH = plotFrequencyResponse(...
                          figH,...
                          config,...
                          inputFunctions,...                                           
                          freqSimData,... 
                          nominalForce,...
                          indexColumn,...
                          subPlotLayout,...
                          referenceDataFolder,...
                          flag_addReferenceData,...
                          0); 

                                                                  
end


