function [figH]= addFittedForceVelocityPlot(figH,...
                    vexatCurves,ehtmmCurves,...
                    expData,umat41,umat43,...
                    keyPointsHL1997,...
                    keyPointsHL2002,...
                    keyPointsVEXATFv,...
                    subPlotPanel,plotSettings)

umat41Color     = plotSettings.umat41.color;
umat41Label     = plotSettings.umat41.label;
umat41LineWidth = plotSettings.umat41.lineWidth;
umat41LineType  = plotSettings.umat41.lineType;

umat43Color     = plotSettings.umat43.color;
umat43Label     = plotSettings.umat43.label;
umat43LineWidth = plotSettings.umat43.lineWidth;
umat43LineType  = plotSettings.umat43.lineType;

HL1997Color     = plotSettings.HL1997.color;
HL1997Label     = plotSettings.HL1997.label;
HL1997LineWidth = plotSettings.HL1997.lineWidth;
HL1997LineType  = plotSettings.HL1997.lineType;

HL2002Color     = plotSettings.HL2002.color;
HL2002Label     = plotSettings.HL2002.label;
HL2002LineWidth = plotSettings.HL2002.lineWidth;
HL2002LineType  = plotSettings.HL2002.lineType;

%Get the fitting RMSE
umat41FpeRMSE = ehtmmCurves.fv.rmse;
umat43FpeRMSE = vexatCurves.fv.rmse;



figure(figH);
    if(length(subPlotPanel)==3)
        subplot(subPlotPanel(1,1),subPlotPanel(1,2),subPlotPanel(1,3));
    end
    if(length(subPlotPanel)==4)
        subplot('Position',subPlotPanel);
    end

    plot(ehtmmCurves.fv.vceNNAT.*umat41.vceMax,...
         ehtmmCurves.fv.fceNAT,...
         plotSettings.umat41.lineType,...
        'Color',umat41Color,...
        'DisplayName',[umat41Label,' $$\mathbf{f}^\mathrm{V}$$'],...
        'LineWidth',umat41LineWidth);
    hold on;

    plot(vexatCurves.fv.vceNNAT.*umat43.vceMax,...
         vexatCurves.fv.fceNAT,...
         plotSettings.umat43.lineType,...
        'Color',umat43Color,...
        'DisplayName',[umat43Label,' $$\mathbf{f}^\mathrm{V}$$'],...
        'LineWidth',umat43LineWidth*0.5);
    hold on;


    plot(keyPointsHL1997.fv.umat43.vceNAT,...
         keyPointsHL1997.fv.umat43.fceNAT,...
         HL1997LineType,...
         'LineWidth',0.5,...
         'MarkerSize',3,...
         'Color',[1,1,1],...
         'MarkerFaceColor',HL1997Color,...
         'DisplayName',HL1997Label);
    hold on;


%    hold on;
%     plot(keyPointsHL2002.fv.vceNAT,...
%          keyPointsHL2002.fv.fceNAT,...
%          HL2002LineType,...
%          'LineWidth',0.5,'Color',[0,0,0],...
%          'MarkerSize',3,...
%          'MarkerFaceColor',HL2002Color,...
%          'DisplayName',HL2002Label);
%     hold on;
    plot(-keyPointsVEXATFv.vceMaxAT,...
         0,...
         'x',...
         'LineWidth',0.5,'Color',[0,0,0],...
         'MarkerSize',3,...
         'MarkerFaceColor',[0,0,0],...
         'HandleVisibility','off');
    hold on;

%     th=text(-keyPointsVEXATFv.vceMax+keyPointsVEXATFv.vceMax*0.05,...
%          0.05,...
%          sprintf('%s%1.2f%s',...
%          '$$v^{\mathrm{M}}_{\mathrm{max}}=$$',...
%          keyPointsVEXATFv.vceMax,...
%          '$$\ell^M_o/s$$'),...
%          'HorizontalAlignment','left',...
%          'VerticalAlignment','bottom',...
%          'Color',umat43Color,...
%          'FontSize',6);
%     hold on;
%     th.Rotation=22.5;

    xright=-keyPointsVEXATFv.vceMaxAT+keyPointsVEXATFv.vceMaxAT*0.05;


    text(xright,1.2,...
        sprintf('%s %1.4f',...
            'RMSE',vexatCurves.fv.rmse),...
            'HorizontalAlignment','left',...
            'VerticalAlignment','top',...
            'Color',umat43Color,...
            'FontSize',6);
    hold on;
    text(xright,1.2-0.075,...
        sprintf('%s %1.4f',...
            'RMSE',ehtmmCurves.fv.rmse),...
            'HorizontalAlignment','left',...
            'VerticalAlignment','top',...
            'Color',umat41Color,...
            'FontSize',6);
    hold on;

    box off;
    
    xlim([min(vexatCurves.fv.vceNNAT).*umat43.vceMax-0.01,...
          max(vexatCurves.fv.vceNNAT).*umat43.vceMax+0.01]);
    ylim(plotSettings.ylim);

    xticks([-round(umat43.vceMax,2),0,round(umat43.vceMax,2)]);
    yticks([0,1,round(umat41.Fecc,2)]);

    xlabel('Norm. Velocity ($$v/\ell^M_o$$)');
    yH = ylabel('Norm. Force ($$f/f^M_o$$)');    
    yH.Position(1) = yH.Position(1) - yH.Position(1)*(1.5/10);  
    title('F. Force velocity fitting $$\mathbf{f}^\mathrm{V}$$');

    [lgdH, lgdIcons, lgdPlots, lgdTxt]=...
        legend('Location','southeast','FontSize',6);

    %[lgdH, lgdIcons, lgdPlots, lgdTxt,xDataOrig,xDataUpd] = ...
    %scaleLegendLines(0.5,lgdH, lgdIcons, lgdPlots, lgdTxt);

    legend boxoff;


