%%
% SPDX-FileCopyrightText: 2024 Matthew Millard <millard.matthew@gmail.com>
%
% SPDX-License-Identifier: MIT
%
%%
function [figH]= addFittedActiveForceLengthPlotV2(...
                    figH,vexatCurves,ehtmmCurves,... 
                    umat41,umat43,...
                    sarcomere,...
                    umat43QuadraticBezierCurves,...
                    keyPointsHL1997,keyPointsHL2002,...
                    subPlotPanel,plotSettings)

umat41Color     = plotSettings.umat41.color;
umat41Label     = plotSettings.umat41.label;
umat41LineWidth = plotSettings.umat41.lineWidth;
umat41LineType  = plotSettings.umat41.lineType;

umat43Color     = plotSettings.umat43.color;
umat43Label     = plotSettings.umat43.label;
umat43LineWidth = plotSettings.umat43.lineWidth;
umat43LineType  = plotSettings.umat43.lineType;

HL1997Color     = plotSettings.HL1997.color;
HL1997Label     = plotSettings.HL1997.label;
HL1997LineWidth = plotSettings.HL1997.lineWidth;
HL1997LineType  = plotSettings.HL1997.lineType;

HL2002Color     = plotSettings.HL2002.color;
HL2002Label     = plotSettings.HL2002.label;
HL2002LineWidth = plotSettings.HL2002.lineWidth;
HL2002LineType  = plotSettings.HL2002.lineType;


figure(figH);
    if(length(subPlotPanel)==3)
        subplot(subPlotPanel(1,1),subPlotPanel(1,2),subPlotPanel(1,3));
    end
    if(length(subPlotPanel)==4)
        subplot('Position',subPlotPanel);
    end



    plot(ehtmmCurves.fl.lceNAT,...
         ehtmmCurves.fl.fceNAT,...
         plotSettings.umat41.lineType,...
        'Color',umat41Color,...
        'DisplayName',[umat41Label,' $$\mathbf{f}^\mathrm{L}$$'],...
        'LineWidth',umat41LineWidth);
    hold on;

    plot(ehtmmCurves.fl.lceNAT,...
         ehtmmCurves.fl.fceNAT+ehtmmCurves.fpe.fceNAT,...
         '--',...
        'Color',umat41Color,...
        'DisplayName',[umat41Label,' $$\mathbf{f}^\mathrm{L}+\mathbf{f}^\mathrm{PE}$$'],...
        'LineWidth',umat41LineWidth*0.5);
    hold on;

    plot(vexatCurves.fl.lceNAT,...
        vexatCurves.fl.fceNAT,...
        plotSettings.umat43.lineType,...
        'Color',umat43Color,...
        'DisplayName',[umat43Label,' $$\mathbf{f}^\mathrm{L}$$'],...
        'LineWidth',umat43LineWidth*0.5);
    hold on;

    plot(vexatCurves.fl.lceNAT,...
        vexatCurves.fl.fceNAT + vexatCurves.fpe.fceNAT,...
        '--',...
        'Color',umat43Color,...
        'DisplayName',[umat43Label,' $$\mathbf{f}^\mathrm{L}+\mathbf{f}^\mathrm{PE}$$'],...
        'LineWidth',umat43LineWidth*0.5);
    hold on;

    plot(keyPointsHL1997.fl.lceNAT,...
         keyPointsHL1997.fl.fceNAT,...
         HL1997LineType,...
         'LineWidth',0.5,...
         'MarkerSize',3,...
         'Color',[1,1,1],...
         'MarkerFaceColor',HL1997Color,...
         'DisplayName',HL1997Label);
    hold on;

    hold on;
    plot(keyPointsHL2002.fl.lceNAT,...
         keyPointsHL2002.fl.fceNAT,...
         HL2002LineType,...
         'LineWidth',0.5,'Color',[0,0,0],...
         'MarkerSize',3,...
         'MarkerFaceColor',HL2002Color,...
         'DisplayName',HL2002Label);
    hold on;

    text(1.8,1-0.075,...
        sprintf('%s %1.4f',...
            'RMSE',ehtmmCurves.fl.rmse),...
            'HorizontalAlignment','right',...
            'VerticalAlignment','top',...
            'Color',umat41Color,...
            'FontSize',6);
    hold on;

    text(1.8,1,...
        sprintf('%s %1.4f',...
            'RMSE',vexatCurves.fl.rmse),...
            'HorizontalAlignment','right',...
            'VerticalAlignment','top',...
            'Color',umat43Color,...
            'FontSize',6);
    hold on;    

    %Points used in the construction of the feline 
    lceN0=sarcomere.normSarcomereLengthZeroForce;
    lceN1=(sarcomere.normActinLength ...
             +sarcomere.normMyosinHalfLength ...
             +sarcomere.normZLineLength)*2;

    xticks(round([lceN0,1,lceN1],2));
    yticks([0,1]);

    box off;
    
    xlim([min(vexatCurves.fl.lceNAT),max(vexatCurves.fl.lceNAT)]);
    ylim(plotSettings.ylim);

    xlabel('Norm. Length ($$\ell/\ell^M_o$$)');
    ylabel('Norm. Force ($$f/f^M_o$$)');    
    title('C. Active force length fitting $$\mathbf{f}^\mathrm{L}$$');

    [lgdH, lgdIcons, lgdPlots, lgdTxt]=...
        legend('Location','south','FontSize',6);

    [lgdH, lgdIcons, lgdPlots, lgdTxt,xDataOrig,xDataUpd] = ...
    scaleLegendLines(0.5,lgdH, lgdIcons, lgdPlots, lgdTxt);

    legend boxoff;

