%%
% SPDX-FileCopyrightText: 2024 Matthew Millard <millard.matthew@gmail.com>
%
% SPDX-License-Identifier: MIT
%
%%
function [figH]= addTitinForceLengthPlot(figH,...
                    vexatCurves,...
                    umat43,...
                    keyPointsHL2002,...
                    sarcomere,...
                    fiberForceLengthCurve,...
                    subPlotPanel,plotSettings)


umat43Color     = plotSettings.umat43.color;
umat43Label     = plotSettings.umat43.label;
umat43LineWidth = plotSettings.umat43.lineWidth;
umat43LineType  = plotSettings.umat43.lineType;


umat43ColorA = umat43Color.*(1-0.75) + [1,1,1].*(0.75);
umat43ColorB = umat43Color.*(1-0.5) + [1,1,1].*(0.5);
umat43ColorC = umat43Color.*(1-0.25) + [1,1,1].*(0.25);


HL2002Color     = plotSettings.HL2002.color;
HL2002Label     = plotSettings.HL2002.label;
HL2002LineWidth = plotSettings.HL2002.lineWidth;
HL2002LineType  = plotSettings.HL2002.lineType;



idxMin = find(vexatCurves.fecm.fceNAT > 0.05,1);

lceNATOne = interp1(vexatCurves.fecm.fceNAT(idxMin:end) ...
                  + vexatCurves.f2.fceNAT(idxMin:end),...
                    vexatCurves.fecm.lceNAT(idxMin:end),1);

idxMin = find(vexatCurves.fpeActiveTitin.fceNAT > 0.05,1);
 

lceNATTwo = interp1(...
    vexatCurves.fpeActiveTitin.fceNAT,...
    vexatCurves.fpeActiveTitin.lceNAT,...
    1);

lcePeZero=fiberForceLengthCurve.xEnd(1,1)+umat43.shiftPEE;

figure(figH);
    if(length(subPlotPanel)==3)
        subplot(subPlotPanel(1,1),subPlotPanel(1,2),subPlotPanel(1,3));
    end
    if(length(subPlotPanel)==4)
        subplot('Position',subPlotPanel);
    end

    ecmFill.lceNAT = [min(vexatCurves.fecm.lceNAT);...
                      max(vexatCurves.fecm.lceNAT);...
                      fliplr(vexatCurves.fecm.lceNAT')';...
                      min(vexatCurves.fecm.lceNAT)];

    ecmFill.fceNAT = [0;...
                      0;...
                      fliplr(vexatCurves.fecm.fceNAT')';...
                      0];

    ecmF2Fill.lceNAT = [vexatCurves.fecm.lceNAT;...
                        fliplr(vexatCurves.f2.lceNAT')';...
                        vexatCurves.fecm.lceNAT(1,1)];

    ecmF2Fill.fceNAT = [vexatCurves.fecm.fceNAT;...
                        fliplr((vexatCurves.f2.fceNAT+vexatCurves.fecm.fceNAT)')';...
                        vexatCurves.fecm.fceNAT(1,1)];

    plot([0,lceNATOne],...
         [1,1].*sarcomere.extraCellularMatrixPassiveForceFraction,...
         '-','Color',[1,1,1].*0.75,...
         'HandleVisibility','off');
    hold on;
    text(min(plotSettings.fpe.xlim),...
        sarcomere.extraCellularMatrixPassiveForceFraction,...
        sprintf('%1.2f',sarcomere.extraCellularMatrixPassiveForceFraction),...
        'HorizontalAlignment','left',...
        'VerticalAlignment','bottom');
    hold on;

    plot([0,lceNATOne],...
         [1,1],...
         '-','Color',[1,1,1].*0.75,...
         'HandleVisibility','off');
    hold on;    

    plot([lceNATOne,lceNATOne],...
         [0,2],...
         '-','Color',[1,1,1].*0.75,...
         'HandleVisibility','off');
    hold on;    

    plot([lceNATTwo,lceNATTwo],...
         [0,2],...
         '-','Color',[1,1,1].*0.75,...
         'HandleVisibility','off');
    hold on;      




    fill(ecmFill.lceNAT,ecmFill.fceNAT,umat43ColorB,...
         'HandleVisibility','off','EdgeColor','none',...
         'FaceAlpha',0.5);
    hold on;

    fill(ecmF2Fill.lceNAT,ecmF2Fill.fceNAT,umat43ColorA,...
         'HandleVisibility','off','EdgeColor','none',...
         'FaceAlpha',0.5);
    hold on;


    plot(vexatCurves.fecm.lceNAT,...
        vexatCurves.fecm.fceNAT,...
        plotSettings.umat43.lineType,...
        'Color',[1,1,1],...
        'HandleVisibility','off',...
        'LineWidth',umat43LineWidth);
    hold on;    
   
    plot(vexatCurves.fecm.lceNAT,...
        vexatCurves.fecm.fceNAT,...
        plotSettings.umat43.lineType,...
        'Color',umat43ColorB,...
        'DisplayName',[umat43Label,' $$\mathbf{f}^\mathrm{ECM}$$'],...
        'HandleVisibility','off',...        
        'LineWidth',umat43LineWidth*0.5);
    hold on;



    plot(vexatCurves.fecm.lceNAT,...
        vexatCurves.fecm.fceNAT+vexatCurves.f2.fceNAT,...
        plotSettings.umat43.lineType,...
        'Color',[1,1,1],...
        'HandleVisibility','off',...
        'LineWidth',umat43LineWidth);
    hold on;

    plot(vexatCurves.fecm.lceNAT,...
        vexatCurves.fecm.fceNAT+vexatCurves.f2.fceNAT,...
        plotSettings.umat43.lineType,...
        'Color',umat43ColorA,...
        'DisplayName',[umat43Label,'Passive: $$\mathbf{f}^\mathrm{ECM} + ',...
                      '(\mathbf{f}^\mathrm{1}||\mathbf{f}^\mathrm{2})$$'],...
        'HandleVisibility','off',...
        'LineWidth',umat43LineWidth*0.5);
    hold on;

    plot(vexatCurves.fpeActiveTitin.lceNAT,...
        vexatCurves.fpeActiveTitin.fceNAT,...
        plotSettings.umat43.lineType,...
        'Color',[1,1,1],...
        'HandleVisibility','off',...                      
        'LineWidth',umat43LineWidth);
    hold on;

    plot(vexatCurves.fpeActiveTitin.lceNAT,...
        vexatCurves.fpeActiveTitin.fceNAT,...
        plotSettings.umat43.lineType,...
        'Color',umat43ColorC,...
        'DisplayName',[umat43Label,' Active: $$\mathbf{f}^\mathrm{ECM} + ',...
                      '(\mathbf{f}^\mathrm{1}||\mathbf{f}^\mathrm{2})$$'],...
        'HandleVisibility','off',...                      
        'LineWidth',umat43LineWidth*0.5);
    hold on;
    


%     plot(lceNATOne,...
%          sarcomere.extraCellularMatrixPassiveForceFraction,...
%          'x','Color',[1,1,1].*0,...
%          'HandleVisibility','off');
%     hold on;
%     plot(lceNATOne,...
%          1,...
%          'x','Color',[1,1,1].*0,...
%          'HandleVisibility','off');
%     hold on;



    plot(keyPointsHL2002.fpe.lceNAT,...
         keyPointsHL2002.fpe.fceNAT,...
         HL2002LineType,...
         'LineWidth',0.5,'Color',[0,0,0],...
         'MarkerSize',3,...
         'MarkerFaceColor',HL2002Color,...
         'DisplayName',HL2002Label);
    hold on;

    dx = (max(vexatCurves.fecm.lceNAT)-min(vexatCurves.fecm.lceNAT))/100;
    dy = diff(plotSettings.ylim)/100;

    x1 = lceNATOne;
    y1 = umat43.lambdaECM;

    th =text(x1-dx,y1-6*dy,...
        'Extracellular Matrix: $$\mathbf{f}^{\mathrm{ECM}}$$',...
        'FontSize',6,...
        'HorizontalAlignment','center',...
        'VerticalAlignment','top');
    th.Rotation = 45;

    hold on;

    th =text(x1+dx,y1+2*dy,...
        'Passive titin: $$\mathbf{f}^{\mathrm{1}}, \mathbf{f}^{\mathrm{2}}$$',...
        'FontSize',6,...
        'HorizontalAlignment','center',...
        'VerticalAlignment','bottom');
    th.Rotation = 45;
    hold on;




    th = text(lceNATTwo+dx,1,...
        'Active titin: $$\mathbf{f}^{\mathrm{2}},\, \mathbf{f}^{\mathrm{ECM}}$$',...
        'FontSize',6,...
        'HorizontalAlignment','right',...
        'VerticalAlignment','top');
    th.Rotation = 70;


    box off;
    


    yticks(round([0, sarcomere.extraCellularMatrixPassiveForceFraction, 1],2));
    yticklabels({'0','$$\lambda$$','1'});


    xticks([round(lcePeZero,2),round(lceNATTwo,2),round(lceNATOne,2)]);
    

    xlim(plotSettings.fpe.xlim);
    ylim(plotSettings.ylim);

    xlabel('Norm. Length ($$\ell/\ell^M_o$$)');
    yH=ylabel('Norm. Force ($$f/f^M_o$$)');    

    yH.Position(1) = yH.Position(1) + yH.Position(1)*(1/40);  

    title(['E. VEXAT Titin fitting $$\mathbf{f}^\mathrm{ECM},\,',...
           '\mathbf{f}^\mathrm{1},\,\mathbf{f}^\mathrm{2}$$']);

    [lgdH, lgdIcons, lgdPlots, lgdTxt]=...
        legend('Location','northwest','FontSize',6);

    %[lgdH, lgdIcons, lgdPlots, lgdTxt,xDataOrig,xDataUpd] = ...
    %scaleLegendLines(0.5,lgdH, lgdIcons, lgdPlots, lgdTxt);
    
    %pos=get(lgdH,'Position');
    %pos(1,1) = pos(1,1)+pos(1,3)*0.2;
    %set(lgdH,'Position',pos);

    legend boxoff;


