function errVec = calcEHTMMPassiveForceLengthError(arg,umat41,...
                        keyPointsHL2002,keyPointsVEXATFpe)

LPEE0   = arg(1,1)*umat41.LPEE0;
FPEE    = arg(2,1)*umat41.FPEE;
nuPEE   = arg(3,1)*umat41.nuPEE;

errVec = zeros(length(keyPointsHL2002.fpe.lceNAT)+2,1);

idx=1;
for i=1:1:length(keyPointsHL2002.fpe.lceNAT)

    lceNAT = keyPointsHL2002.fpe.lceNAT(i,1);
    lceAT  = lceNAT*umat41.lceOptAT;

    fpeAT= calcFpeeUmat41(lceAT,...
                        umat41.lceOptAT,...
                        umat41.dWdes,...
                        umat41.fceOptAT,...
                        FPEE,...
                        LPEE0,...
                        nuPEE);

    fpeNAT = fpeAT/umat41.fceOptAT;

    errVec(idx,1) = fpeNAT - keyPointsHL2002.fpe.fceNAT(i,1);
    idx=idx+1;
end

lceNAT = keyPointsVEXATFpe.lceNAT;
lceAT  = lceNAT*umat41.lceOptAT; 
fpeAT= calcFpeeUmat41(lceAT,...
                    umat41.lceOptAT,...
                    umat41.dWdes,...
                    umat41.fceOptAT,...
                    FPEE,...
                    LPEE0,...
                    nuPEE);
fpeNAT = fpeAT/umat41.fceOptAT;
errVec(idx,1) = fpeNAT - keyPointsVEXATFpe.fceNAT;
idx=idx+1;

kpeAT= calcFpeeDerivativeUmat41(lceAT,...
                    umat41.lceOptAT,...
                    umat41.dWdes,...
                    umat41.fceOptAT,...
                    FPEE,...
                    LPEE0,...
                    nuPEE);
kpeNAT = kpeAT/(umat41.fceOptAT/umat41.lceOptAT);

errVec(idx,1)=kpeNAT - keyPointsVEXATFpe.kceNAT; 
