function errVec = calcEHTMMPassiveForceLengthError(...
                        arg,...
                        umat41,...
                        keyPointsHL2002,...
                        keyPointsHL1997,...
                        keyPointsVEXATFpe,...
                        vexatFpeSample,...
                        fitMode)

if(fitMode==1)
    LPEE0   = arg(1,1)*umat41.LPEE0;
    FPEE    = arg(2,1)*umat41.FPEE;
    nuPEE   = arg(3,1)*umat41.nuPEE;
    
    errVec = zeros(length(keyPointsHL2002.fpe.lceNAT)+2,1);
    
    idx=1;
    for i=1:1:length(keyPointsHL2002.fpe.lceNAT)

        lceNAT = keyPointsHL2002.fpe.lceNAT(i,1);
        lceAT  = lceNAT*umat41.lceOptAT;
    
        fpeAT= calcFpeeUmat41(lceAT,...
                            umat41.lceOptAT,...
                            umat41.dWdes,...
                            umat41.fceOptAT,...
                            FPEE,...
                            LPEE0,...
                            nuPEE);
    
        fpeNAT = fpeAT/umat41.fceOptAT;
    
        errVec(idx,1) = fpeNAT - keyPointsHL2002.fpe.fceNAT(i,1);
        idx=idx+1;
    end
    
    lceNAT = keyPointsVEXATFpe.lceNAT;
    lceAT  = lceNAT*umat41.lceOptAT; 
    fpeAT= calcFpeeUmat41(lceAT,...
                        umat41.lceOptAT,...
                        umat41.dWdes,...
                        umat41.fceOptAT,...
                        FPEE,...
                        LPEE0,...
                        nuPEE);
    fpeNAT = fpeAT/umat41.fceOptAT;
    errVec(idx,1) = fpeNAT - keyPointsVEXATFpe.fceNAT;
    idx=idx+1;
    
    kpeAT= calcFpeeDerivativeUmat41(lceAT,...
                        umat41.lceOptAT,...
                        umat41.dWdes,...
                        umat41.fceOptAT,...
                        FPEE,...
                        LPEE0,...
                        nuPEE);
    kpeNAT = kpeAT/(umat41.fceOptAT/umat41.lceOptAT);
    
    errVec(idx,1)=kpeNAT - keyPointsVEXATFpe.kceNAT; 

end

if(fitMode==2)

    LPEE0   = arg(1,1)*umat41.LPEE0;
    FPEE    = arg(2,1)*umat41.FPEE;
    nuPEE   = arg(3,1)*umat41.nuPEE;
    
    errVec = zeros(3+floor(length(vexatFpeSample.lceNAT)/10),1);
    %%
    %HL2002: single point from the FPE measurement
    %%
    idx=1;
    k = kmeans(keyPointsHL1997.fpe.lceNAT,keyPointsHL1997.fpe.clusters);
    meanLceNAT = zeros(max(k),1);
    meanFceNAT = zeros(max(k),1);
    for i=1:1:max(k)
        idxCluster = find(k==i);
        meanLceNAT(i,1) = mean(keyPointsHL1997.fpe.lceNAT(idxCluster,1));
        meanFceNAT(i,1) = mean(keyPointsHL1997.fpe.fceNAT(idxCluster,1));
    end
    [lceNAT1,idx1] =max(meanLceNAT);
    fceNAT1 = meanFceNAT(idx1);

    lceAT = lceNAT1*umat41.lceOptAT;

    fpeAT= calcFpeeUmat41(lceAT,...
                        umat41.lceOptAT,...
                        umat41.dWdes,...
                        umat41.fceOptAT,...
                        FPEE,...
                        LPEE0,...
                        nuPEE);

    fpeNAT = fpeAT/umat41.fceOptAT;
    errVec(idx,1) = fpeNAT - fceNAT1;

    %%
    %VEXAT: length that develops 1 fiso
    %%
    idx=idx+1;


    lceNAT = keyPointsVEXATFpe.lceNAT;
    lceAT  = lceNAT*umat41.lceOptAT; 
    fpeAT= calcFpeeUmat41(lceAT,...
                        umat41.lceOptAT,...
                        umat41.dWdes,...
                        umat41.fceOptAT,...
                        FPEE,...
                        LPEE0,...
                        nuPEE);
    fpeNAT = fpeAT/umat41.fceOptAT;
    errVec(idx,1) = fpeNAT - keyPointsVEXATFpe.fceNAT;
    
    %%
    %VEXAT: stiffness at 1 fiso
    %%
    idx=idx+1;   
    kpeAT= calcFpeeDerivativeUmat41(lceAT,...
                        umat41.lceOptAT,...
                        umat41.dWdes,...
                        umat41.fceOptAT,...
                        FPEE,...
                        LPEE0,...
                        nuPEE);
    kpeNAT = kpeAT/(umat41.fceOptAT/umat41.lceOptAT);
    
    errVec(idx,1)=kpeNAT - keyPointsVEXATFpe.kceNAT;     

    %%
    % VEXAT Sample
    %%

    fmin = 0.1;
    fmax = 0.6;
    idxMin = find(vexatFpeSample.fceNAT > fmin*0.5,1);
    for k=1:1:8
        
        n = (k-1)/(8-1);
        fsample = fmin + n*(fmax-fmin);        
        lceNAT = interp1(vexatFpeSample.fceNAT(idxMin:end),...
                         vexatFpeSample.lceNAT(idxMin:end),...
                         fsample);

        lceAT  = lceNAT*umat41.lceOptAT; 
        fpeAT= calcFpeeUmat41(lceAT,...
                            umat41.lceOptAT,...
                            umat41.dWdes,...
                            umat41.fceOptAT,...
                            FPEE,...
                            LPEE0,...
                            nuPEE);
        fpeNAT = fpeAT/umat41.fceOptAT;
        errVec(idx,1) = fpeNAT - fsample;
        idx=idx+1;
    end

    here=1;
end