function umat41= fitEHTMMPassiveForceLengthRelation(...
        expData,umat41,...
        keyPointsHL1997, keyPointsHL2002,...
        keyPointsVEXATFpe,...
        flag_plotEHTMMPassiveForceLengthFitting)

assert(contains(expData,'HL1997')==0,'Error: Need to add HL1997 fpe fit');

errFcn = @(arg)calcEHTMMPassiveForceLengthError(arg,umat41,...
                        keyPointsHL2002,keyPointsVEXATFpe);

x0 = [0.6;0.5;4]./[umat41.LPEE0;umat41.FPEE;umat41.nuPEE];

options     = optimset('Display','off','MaxIter',1e6);
[x1, resnorm,residual,exitflag]   = lsqnonlin(errFcn,x0,[],[],options);
assert(exitflag==1 || exitflag==3);

LPEE0   = x1(1,1)*umat41.LPEE0;
FPEE    = x1(2,1)*umat41.FPEE;
nuPEE   = x1(3,1)*umat41.nuPEE;

umat41.LPEE0 = LPEE0;
umat41.FPEE  = FPEE;
umat41.nuPEE = nuPEE;

if(flag_plotEHTMMPassiveForceLengthFitting==1)
    lceNAT   = [0.8:0.01:1.4]';
    fpeNAT   = zeros(size(lceNAT)); 
 
    for i=1:1:length(lceNAT)
        lceAT = lceNAT(i,1)*umat41.lceOptAT;
        fpeAT= calcFpeeUmat41(lceAT,...
                            umat41.lceOptAT,...
                            umat41.dWdes,...
                            umat41.fceOptAT,...
                            FPEE,...
                            LPEE0,...
                            nuPEE);

        fpeNAT(i,1) = fpeAT/umat41.fceOptAT;        
    end

    lceATOne = calcFpeeInverseUmat41(umat41.fceOptAT,...
                            umat41.lceOptAT,...
                            umat41.dWdes,...
                            umat41.fceOptAT,...
                            FPEE,...
                            LPEE0,...
                            nuPEE);
    lceNATOne = lceATOne/umat41.lceOptAT;
    fceATOne = calcFpeeUmat41(lceATOne,...
                            umat41.lceOptAT,...
                            umat41.dWdes,...
                            umat41.fceOptAT,...
                            FPEE,...
                            LPEE0,...
                            nuPEE);
    fceNATOne= fceATOne/umat41.fceOptAT;
    kceATOne  = calcFpeeDerivativeUmat41(lceATOne,...
                            umat41.lceOptAT,...
                            umat41.dWdes,...
                            umat41.fceOptAT,...
                            FPEE,...
                            LPEE0,...
                            nuPEE);
    kceNATOne = kceATOne/(umat41.fceOptAT/umat41.lceOptAT);

    figEHTMMFpe=figure;
    plot(lceNAT,fpeNAT,'-k','DisplayName','EHTMM');
    hold on;
    switch expData
        case 'HL1997'
            plot(keyPointsHL1997.fpe.lceNAT,...
                 keyPointsHL1997.fpe.fceNAT,'ok',...
                 'DisplayName','HL1997');
            hold on;
            plot(keyPointsHL2002.fpe.lceNAT,...
                 keyPointsHL2002.fpe.fceNAT,'xk',...
                 'DisplayName','HL2002');
            hold on;                
        case 'HL2002'
            plot(keyPointsHL2002.fpe.lceNAT,...
                 keyPointsHL2002.fpe.fceNAT,'xk',...
                 'DisplayName','HL2002');
            hold on;                
    end
    plot(keyPointsVEXATFpe.lceNAT,...
         keyPointsVEXATFpe.fceNAT,'.b','MarkerFaceColor',[0,0,0]);
    hold on;
    text(keyPointsVEXATFpe.lceNAT+0.013,keyPointsVEXATFpe.fceNAT,...
         sprintf('VEXAT: %1.3f fceOpt/lceOpt',keyPointsVEXATFpe.kceNAT),...
         'HorizontalAlignment','left');
    hold on;

    plot(lceNATOne,...
         fceNATOne,'.r','MarkerFaceColor',[0,0,1]);
    hold on;
    text(lceNATOne-0.013,fceNATOne,...
         sprintf('EHTMM: %1.3f fceOpt/lceOpt',kceNATOne),...
         'HorizontalAlignment','right');
    hold on;

    xlabel('Norm. Length ($$\ell/\ell^M_o$$');
    ylabel('Norm. Force ($$f/f^M_o$$');
    title('EHTMM Passive force-length relation fitting');       

end
