%%
% SPDX-FileCopyrightText: 2024 Matthew Millard <millard.matthew@gmail.com>
%
% SPDX-License-Identifier: MIT
%
%%
function [umat41, ehtmmCurves] = ...
        fitEHTMMActivePassiveForceLengthRelation(...
           expData, ...
           umat41, ...
           umat41HL2002,...
           keyPointsHL1997,...
           keyPointsHL2002,...
           keyPointsVEXATFpe,...
           vexatFpeSample,...
           ehtmmCurves,...
           flag_plotEHTMMActivePassiveForceLengthFitting)



%Fit active and passive terms. Here HL1997 and HL2002 share the same
%active force-length curve but have different passive-force-length curves
switch expData
    case 'HL1997'
        %Just fit the passive terms
        x0 = ones(3,1);
        lb = ones(3,1).*1/3;
        ub = ones(3,1).*3;
        umat41.dWdes    = umat41HL2002.dWdes;
        umat41.nuCEdes  = umat41HL2002.nuCEdes;
        umat41.dWasc    = umat41HL2002.dWasc;
        umat41.nuCEasc  = umat41HL2002.nuCEasc;

    case 'HL2002'
        %Fit the active and passive terms.
        x0 = ones(7,1);
        lb = ones(7,1).*1/3;
        ub = ones(7,1).*3;        
end

errFcn = @(arg)calcEHTMMActivePassiveError(...
                    arg,...
                    umat41,...
                    keyPointsHL1997,...
                    keyPointsHL2002,...
                    keyPointsVEXATFpe,...
                    vexatFpeSample,...
                    expData);

options=optimset('Display','off');
[x1, resnorm,residual,exitflag] = ...
    lsqnonlin(errFcn,x0,lb,ub,options);

errSoln =calcEHTMMActivePassiveError(...
                    x1,...
                    umat41,...
                    keyPointsHL1997,...
                    keyPointsHL2002,...
                    keyPointsVEXATFpe,...
                    vexatFpeSample,...
                    expData);

switch expData
    case 'HL1997'
        %Just fit the passive terms
        umat41.LPEE0    = x1(1,1)*umat41.LPEE0;
        umat41.FPEE     = x1(2,1)*umat41.FPEE;
        umat41.nuPEE    = x1(3,1)*umat41.nuPEE;   

    case 'HL2002'
        %Fit the active and passive terms.
        umat41.dWdes    = x1(1,1)*umat41.dWdes;
        umat41.nuCEdes  = x1(2,1)*umat41.nuCEdes;
        umat41.dWasc    = x1(3,1)*umat41.dWasc;
        umat41.nuCEasc  = x1(4,1)*umat41.nuCEasc;
        umat41.LPEE0    = x1(5,1)*umat41.LPEE0;
        umat41.FPEE     = x1(6,1)*umat41.FPEE;
        umat41.nuPEE    = x1(7,1)*umat41.nuPEE;        
end






switch expData
    case 'HL1997'
        idxFl  = [1:1:length(keyPointsHL1997.fl.l)];
        idxFpe = [1:1:(length(keyPointsHL1997.fpe.l)+3)]'+max(idxFl);

    case 'HL2002'
        idxMaxFal = length(keyPointsHL1997.fl.l)+length(keyPointsHL2002.fl.l);
        idxFl   = [1:1:idxMaxFal]';
        
        idxA = max(idxMaxFal);
        idxFpe = [1:1:(length(keyPointsHL2002.fpe.l)+2)]'+idxA; 
       
    otherwise
        assert(0,'Error: expData must be HL1997 or HL2002');
end

rmse.fl     = sqrt(mean( errSoln(idxFl).^2));
rmse.fpe    = sqrt(mean(errSoln(idxFpe).^2));

%%
% Sample the curves of the model:
%  fl,fpe
%%

npts = length(vexatFpeSample.lceNAT);
ehtmmCurves.fpe.lceNAT = vexatFpeSample.lceNAT;
ehtmmCurves.fpe.fceNAT = zeros(size(vexatFpeSample.lceNAT));
ehtmmCurves.fpe.rmse = rmse.fpe;


ehtmmCurves.fl.lceNAT = vexatFpeSample.lceNAT;
ehtmmCurves.fl.fceNAT = zeros(size(vexatFpeSample.lceNAT));
ehtmmCurves.fl.rmse = rmse.fl;

for i=1:1:npts 
    lceNAT = ehtmmCurves.fpe.lceNAT(i,1);
    lceAT = lceNAT*umat41.lceOptAT;

    ehtmmCurves.fl.fceNAT(i,1) = calcFisomUmat41(lceAT, ...
                                    umat41.lceOptAT,...
                                    umat41.dWdes,...
                                    umat41.nuCEdes, ...
                                    umat41.dWasc, ...
                                    umat41.nuCEasc);

    ehtmmCurves.fpe.fceNAT(i,1) = calcFpeeUmat41(lceAT, ...
                                        umat41.lceOptAT,...
                                        umat41.dWdes,...
                                        umat41.fceOptAT,...
                                        umat41.FPEE,...
                                        umat41.LPEE0,...
                                        umat41.nuPEE);
    ehtmmCurves.fpe.fceNAT(i,1) = ehtmmCurves.fpe.fceNAT(i,1)/umat41.fceOptAT;


end

ehtmmCurves.fpe.kceNAT = calcCentralDifferenceDataSeries(...
                            ehtmmCurves.fpe.lceNAT,...
                            ehtmmCurves.fpe.fceNAT);


if(flag_plotEHTMMActivePassiveForceLengthFitting==1)
    figActivePassiveForceLength=figure;

        plot(ehtmmCurves.fl.lceNAT,...
             ehtmmCurves.fl.fceNAT,'-',...
             'Color',[1,1,1].*0.25,...
             'DisplayName','fl');
        hold on;
        plot(ehtmmCurves.fpe.lceNAT,...
             ehtmmCurves.fpe.fceNAT,...
             '-','Color',[1,1,1].*0.5,...
             'DisplayName','fpe');
        hold on;        
        plot(ehtmmCurves.fl.lceNAT,...
             ehtmmCurves.fl.fceNAT+ehtmmCurves.fpe.fceNAT,...
             '-','Color',[1,1,1].*0,...
             'DisplayName','fl+fpe');
        hold on;        

        plot(keyPointsHL1997.fl.lceNAT,...
             keyPointsHL1997.fl.fceNAT,'xr',...
             'DisplayName','HL1997 fl');
        hold on;
        plot(keyPointsHL1997.fpe.lceNAT,...
             keyPointsHL1997.fpe.fceNAT,'or',...
             'DisplayName','HL1997 fpe');
        hold on;
        
        plot(keyPointsHL2002.fl.lceNAT,...
             keyPointsHL2002.fl.fceNAT,'xb',...
             'DisplayName','HL2002 fl');
        hold on;

        plot(keyPointsHL2002.fpe.lceNAT,...
             keyPointsHL2002.fpe.fceNAT,'ob',...
             'DisplayName','HL2002 fpe');
        hold on;   


        text(0.45,1.15,...
             sprintf('%1.2e RMSE fl\n%1.2e RMSE fpe\n',...
                        ehtmmCurves.fl.rmse,...
                        ehtmmCurves.fpe.rmse),...
             'HorizontalAlignment','left',...
             'VerticalAlignment','top',...
             'FontSize',8)
        hold on;
        switch expData
            case 'HL1997'
                text(0.75,0.8,...
                    sprintf('%1.3f %s\n%1.3f %s\n%1.3f %s\n%1.3f %s\n',...
                    umat41.fceOpt,'$$f^M_o$$',umat41.lceOpt,'$$\ell^M_o$$',...
                    umat41.ltSlk,'$$\ell^T_s$$',umat41.lp0HL1997,'$$\ell^P_0$$'),...
                    'FontSize',12,...
                    'VerticalAlignment','top');
                hold on;

            case 'HL2002'
                text(0.75,0.8,...
                    sprintf('%1.3f %s\n%1.3f %s\n%1.3f %s\n%1.3f %s\n',...
                    umat41.fceOpt,'$$f^M_o$$',umat41.lceOpt,'$$\ell^M_o$$',...
                    umat41.ltSlk,'$$\ell^T_s$$',umat41.lp0HL2002,'$$\ell^P_0$$'),...
                    'FontSize',12,...
                    'VerticalAlignment','top');
                hold on;
        end
        box off;
        xlabel('Norm. Length ($$\ell/\ell^M_o$$)');
        ylabel('Norm. Force ($$f/f^M_o$$)');
        xlim([0.4,1.6]);
        ylim([0,1.2]);
        here=1;
end

