function [umat41, ehtmmCurves ]= ...
    fitEHTMMPassiveForceLengthRelation(...
        expData,...
        umat41,...
        keyPointsHL1997, ...
        keyPointsHL2002,...
        keyPointsVEXATFpe,...
        ehtmmCurves,...
        vexatCurves,...
        flag_plotEHTMMPassiveForceLengthFitting)



fitMode=1;
errFcn = @(arg)calcEHTMMPassiveForceLengthError(arg,umat41,...
                        keyPointsHL2002,keyPointsHL1997,...
                        keyPointsVEXATFpe,vexatCurves.fpe,...
                        fitMode);



x0 = [1;1;1];

%Strange solutions result when LPEE0 is greater than the smallest data
%point
LPEE0init   = 0.75*min(keyPointsHL2002.fpe.umat41.lceNAT);
x0(1,1) = LPEE0init/umat41.LPEE0;

options     = optimset('Display','off','MaxIter',1e6);
[x1, resnorm,residual,exitflag]   = lsqnonlin(errFcn,x0,[],[],options);
assert(exitflag==1 || exitflag==3);

LPEE0   = x1(1,1)*umat41.LPEE0;
FPEE    = x1(2,1)*umat41.FPEE;
nuPEE   = x1(3,1)*umat41.nuPEE;


if(contains(expData,'HL1997'))
    fitMode=2;
    errFcn2 = @(arg)calcEHTMMPassiveForceLengthError(arg,umat41,...
                            keyPointsHL2002,keyPointsHL1997,...
                            keyPointsVEXATFpe,vexatCurves.fpe,...
                            fitMode);
    
    LPEE0init = min(keyPointsHL1997.fpe.umat41.lceNAT)*0.75;
    x0 = x1;
    x0(1,1) = LPEE0init/umat41.LPEE0;
    
    
    options     = optimset('Display','off','MaxIter',1e6);
    [x1, resnorm,residual,exitflag]   = lsqnonlin(errFcn2,x0,[],[],options);
    assert(exitflag==1 || exitflag==3);
    
    LPEE0   = x1(1,1)*umat41.LPEE0;
    FPEE    = x1(2,1)*umat41.FPEE;
    nuPEE   = x1(3,1)*umat41.nuPEE;    

end

umat41.LPEE0 = LPEE0;
umat41.FPEE  = FPEE;
umat41.nuPEE = nuPEE;

lceNAT   = [0.7:0.01:1.4]';
fpeNAT   = zeros(size(lceNAT)); 
kpeNAT   = zeros(size(lceNAT)); 




for i=1:1:length(lceNAT)
    lceAT = lceNAT(i,1)*umat41.lceOptAT;
    fpeAT= calcFpeeUmat41(lceAT,...
                        umat41.lceOptAT,...
                        umat41.dWdes,...
                        umat41.fceOptAT,...
                        FPEE,...
                        LPEE0,...
                        nuPEE);
    kpeAT= calcFpeeDerivativeUmat41(lceAT,...
                        umat41.lceOptAT,...
                        umat41.dWdes,...
                        umat41.fceOptAT,...
                        FPEE,...
                        LPEE0,...
                        nuPEE);

    fpeNAT(i,1) = fpeAT/umat41.fceOptAT;      
    kpeNAT(i,1) = kpeAT/(umat41.fceOptAT/umat41.lceOptAT);
end

lceATOne = calcFpeeInverseUmat41(umat41.fceOptAT,...
                        umat41.lceOptAT,...
                        umat41.dWdes,...
                        umat41.fceOptAT,...
                        FPEE,...
                        LPEE0,...
                        nuPEE);
lceNATOne = lceATOne/umat41.lceOptAT;
fceATOne = calcFpeeUmat41(lceATOne,...
                        umat41.lceOptAT,...
                        umat41.dWdes,...
                        umat41.fceOptAT,...
                        FPEE,...
                        LPEE0,...
                        nuPEE);
fceNATOne= fceATOne/umat41.fceOptAT;
kceATOne  = calcFpeeDerivativeUmat41(lceATOne,...
                        umat41.lceOptAT,...
                        umat41.dWdes,...
                        umat41.fceOptAT,...
                        FPEE,...
                        LPEE0,...
                        nuPEE);
kceNATOne = kceATOne/(umat41.fceOptAT/umat41.lceOptAT);

ehtmmCurves.fpe.lceNAT = lceNAT;
ehtmmCurves.fpe.fceNAT = fpeNAT;
ehtmmCurves.fpe.kceNAT = kpeNAT;
ehtmmCurves.fpe.rmse = sqrt(mean(residual.^2));


if(flag_plotEHTMMPassiveForceLengthFitting==1)    
    figEHTMMFpe=figure;
    plot(lceNAT,fpeNAT,'-k','DisplayName','EHTMM');
    hold on;
    switch expData
        case 'HL1997'
            plot(keyPointsHL1997.fpe.umat41.lceNAT,...
                 keyPointsHL1997.fpe.umat41.fceNAT,'ok',...
                 'DisplayName','HL1997 (umat41 tdn)');
            hold on;
            plot(keyPointsHL2002.fpe.umat41.lceNAT,...
                 keyPointsHL2002.fpe.umat41.fceNAT,'xk',...
                 'DisplayName','HL2002 (umat41 tdn)');
            hold on; 

            plot(keyPointsHL1997.fpe.umat43.lceNAT,...
                 keyPointsHL1997.fpe.umat43.fceNAT,'or',...
                 'DisplayName','HL1997 (umat43 tdn)');
            hold on;
            plot(keyPointsHL2002.fpe.umat43.lceNAT,...
                 keyPointsHL2002.fpe.umat43.fceNAT,'xr',...
                 'DisplayName','HL2002 (umat43 tdn)');
            hold on; 


        case 'HL2002'
            plot(keyPointsHL2002.fpe.umat41.lceNAT,...
                 keyPointsHL2002.fpe.umat41.fceNAT,'xk',...
                 'DisplayName','HL2002 (umat41 tdn)');
            hold on; 

            plot(keyPointsHL2002.fpe.umat43.lceNAT,...
                 keyPointsHL2002.fpe.umat43.fceNAT,'xr',...
                 'DisplayName','HL2002 (umat43 tdn)');
            hold on; 
    end
    plot(keyPointsVEXATFpe.lceNAT,...
         keyPointsVEXATFpe.fceNAT,'.b','MarkerFaceColor',[0,0,0]);
    hold on;
    text(keyPointsVEXATFpe.lceNAT+0.013,keyPointsVEXATFpe.fceNAT,...
         sprintf('VEXAT: %1.3f fceOpt/lceOpt',keyPointsVEXATFpe.kceNAT),...
         'HorizontalAlignment','left',...
         'VerticalAlignment','bottom',...
         'Color',[0,0,1]);
    hold on;

    plot(lceNATOne,...
         fceNATOne,'.r','MarkerFaceColor',[0,0,1]);
    hold on;
    text(lceNATOne-0.013,fceNATOne,...
         sprintf('EHTMM: %1.3f fceOpt/lceOpt',kceNATOne),...
         'HorizontalAlignment','right',...
         'VerticalAlignment','top',...
         'Color',[1,0,0]);
    hold on;

    xlabel('Norm. Length ($$\ell/\ell^M_o$$');
    ylabel('Norm. Force ($$f/f^M_o$$');
    title('EHTMM Passive force-length relation fitting');       

end
