function umat43 = fitVEXATPassiveForceLengthRelation(expData,...
                    umat43,...
                    keyPointsHL1997, keyPointsHL2002,...
                    fiberForceLengthCurve,...
                    flag_plotVEXATPassiveForceLengthFitting)

