function success = updateFittedPassiveForceLengthPlot(figFileName,...
                    vexatCurves,...
                    ehtmmCurves,...          
                    expData,...        
                    umat41,...
                    umat43,...
                    keyPointsHL1997, ...
                    keyPointsHL2002, ...
                    keyPointsVEXATFpe,...
                    subPlotPanel,...
                    plotSettings)


figH = openfig(figFileName);

umat41Color     = plotSettings.umat41.color;
umat41Label     = plotSettings.umat41.label;
umat41LineWidth = plotSettings.umat41.lineWidth;
umat41LineType  = plotSettings.umat41.lineType;

umat43Color     = plotSettings.umat43.color;
umat43Label     = plotSettings.umat43.label;
umat43LineWidth = plotSettings.umat43.lineWidth;
umat43LineType  = plotSettings.umat43.lineType;

HL1997Color     = plotSettings.HL1997.color;
HL1997Label     = plotSettings.HL1997.label;
HL1997LineWidth = plotSettings.HL1997.lineWidth;
HL1997LineType  = plotSettings.HL1997.lineType;

HL2002Color     = plotSettings.HL2002.color;
HL2002Label     = plotSettings.HL2002.label;
HL2002LineWidth = plotSettings.HL2002.lineWidth;
HL2002LineType  = plotSettings.HL2002.lineType;


idxMin = find(ehtmmCurves.fpe.fceNAT > 0.05,1);

lceNATOne = interp1(ehtmmCurves.fpe.fceNAT(idxMin:end),...
                    ehtmmCurves.fpe.lceNAT(idxMin:end),1);
fceNATOne  = interp1(ehtmmCurves.fpe.lceNAT(idxMin:end),...
                    ehtmmCurves.fpe.fceNAT(idxMin:end),lceNATOne);
kceNATOne  = interp1(ehtmmCurves.fpe.lceNAT(idxMin:end),...
                    ehtmmCurves.fpe.kceNAT(idxMin:end),lceNATOne);


figure(figH);

if(length(subPlotPanel)==3)
    subplot(subPlotPanel(1,1),subPlotPanel(1,2),subPlotPanel(1,3));
end
if(length(subPlotPanel)==4)
    subplot('Position',subPlotPanel);
end


plot(ehtmmCurves.fpe.lceNAT,...
     ehtmmCurves.fpe.fceNAT,...
     '--',...
    'Color',umat41Color,...
    'DisplayName',[umat41Label,' $$\mathbf{f}^\mathrm{PE}$$'],...
    'LineWidth',umat41LineWidth,...
    'HandleVisibility','off');
hold on;

plot(vexatCurves.fpe.lceNAT,...
    vexatCurves.fpe.fceNAT,...
    '--',...
    'Color',umat43Color,...
    'DisplayName',[umat43Label,' $$\mathbf{f}^\mathrm{PE}$$'],...
    'LineWidth',umat43LineWidth*0.5,...
    'HandleVisibility','off');
hold on;

plot(keyPointsHL1997.fpe.umat43.lceNAT,...
     keyPointsHL1997.fpe.umat43.fceNAT,...
     HL1997LineType,...
     'LineWidth',0.5,...
     'MarkerSize',3,...
     'Color',[1,1,1],...
     'MarkerFaceColor',HL1997Color,...
     'DisplayName',HL1997Label);
hold on;

%The stiffness annotation is a bit misleading:
% The values change because the values of lceOpt and fceOpt change
% between HL2002 and HL1997. However, the stiffness of the fpe curve
% for HL1997 is just a shifted version of the HL2002 curve ... and the 
% stiffness values are very similar when lceOpt and fceOpt are the same.

flag_addText=0;
if(flag_addText==1)
    ytext = keyPointsVEXATFpe.fceNAT-0.3;
    text(keyPointsVEXATFpe.lceNAT-0.1,...
         ytext,...
         sprintf('%s%1.2f%s',...
         '$$k^{PE}_o=$$',...
         keyPointsVEXATFpe.kceNAT,...
         '$$f^M_o/\ell^M_o$$'),...
         'HorizontalAlignment','right',...
         'VerticalAlignment','top',...
         'Color',umat43Color,...
         'FontSize',6);
    hold on;

    text(keyPointsVEXATFpe.lceNAT-0.1,...
         ytext-0.075,...
         sprintf('%s%1.2f%s',...
         '$$k^{PE}_o=$$',...
         kceNATOne,...
         '$$f^M_o/\ell^M_o$$'),...
         'HorizontalAlignment','right',...
         'VerticalAlignment','top',...
         'Color',umat41Color,...
         'FontSize',6);
    hold on;
end

figure(figH);      
figH=configPlotExporter(figH, ...
            plotSettings.pageWidth, plotSettings.pageHeight);
idx=strfind(figFileName,'HL2002');

fileName =  [figFileName(1,1:(idx-1)),'HL2002_HL1997',figFileName((idx+6):end)] ;
fileName = fileName(1:(end-4));

print('-dpdf', [fileName,'.pdf']);

saveas(figH,fileName,'fig');

success=1;