function success = writeAllLSDYNAMuscleParameterFiles(...
                        commonParameterFolder,expAbbrv,...
                        mat156,umat41,umat43,...
                        umat43KBR1994ExtraLines)

mat156ParameterFile = fullfile(commonParameterFolder,...
                      ['catsoleus',expAbbrv,'Mat156Parameters.k']);

umat41ParameterFile = fullfile(commonParameterFolder,...
                      ['catsoleus',expAbbrv,'Umat41Parameters.k']);

umat43ParameterFile = fullfile(commonParameterFolder,...
                      ['catsoleus',expAbbrv,'Umat43Parameters.k']);


success156  = writeLSDYNAMuscleParameterFile(mat156ParameterFile,...
                                             mat156,mat156.extraLines);
success41   = writeLSDYNAMuscleParameterFile(umat41ParameterFile,...
                                             umat41,umat41.extraLines);
success43   = writeLSDYNAMuscleParameterFile(umat43ParameterFile,...
                                             umat43,umat43.extraLines);


if(contains(expAbbrv,'HL2002'))
    umat43KBR1994Fig3ParameterFile = fullfile(commonParameterFolder,...
                    ['catsoleusKBR1994Fig3Umat43Parameters.k']);

    success43KBR1994Fig3   = writeLSDYNAMuscleParameterFile(...
                                umat43KBR1994Fig3ParameterFile,...
                                umat43,...
                                umat43KBR1994ExtraLines.kbr1994Fig3);

    umat43KBR1994Fig12ParameterFile = fullfile(commonParameterFolder,...
                    ['catsoleusKBR1994Fig12Umat43Parameters.k']);

    success43KBR1994Fig12  = writeLSDYNAMuscleParameterFile(...
                                umat43KBR1994Fig12ParameterFile,...
                                umat43,...
                                umat43KBR1994ExtraLines.kbr1994Fig12);    
end


success = (success156 && success41 && success43);






